<?php

$app->dbh->exec("INSERT INTO `DD_FORMULAIREQUESTIONTYPE` (`QTY_CODE`, `QTY_LIBELLE`, `QTY_GROUPE`) VALUES
('QTY_CHECKBOX', '@fr_FR:Case à cocher@en_US:Checkbox@', 'Input'),
('QTY_DATE', '@fr_FR:Date@en_US:Date@', 'Input'),
('QTY_EMAIL', '@fr_FR:Email@en_US:Mail@', 'Input'),
('QTY_EMAIL_NOTIF', '@fr_FR:Email accusé réception@en_US:Notification mail@', 'Input'),
('QTY_FILE', '@fr_FR:Fichier@en_US:File@', 'Input'),
('QTY_INFORMATION', '@fr_FR:Information@en_US:Additional information@', 'Information'),
('QTY_LIST', '@fr_FR:Liste@en_US:List@', 'Input'),
('QTY_RADIO', '@fr_FR:Bouton radio@en_US:Radio button@', 'Input'),
('QTY_SELECT', '@fr_FR:Liste déroulante@en_US:Drop list@', 'Input'),
('QTY_TEXT', '@fr_FR:Texte@en_US:Text@', 'Input'),
('QTY_TEXTAREA', '@fr_FR:Texte multiligne@en_US:Multi-lines text@', 'Input'),
('QTY_URL', '@fr_FR:URL@en_US:URL@', 'Input'),
('QTY_TEL', '@fr_FR:Téléphone@en_US:Telephone@', 'Input'),
('QTY_SELECTEMAIL', '@fr_FR:Liste destinataires (emails)@en_US:Recipient(email)@', 'Input'),
('QTY_CAPTCHAGRAPHIC', '@fr_FR:Captcha graphique@en_US:Graphical captcha@', 'Captcha'),
('QTY_CAPTCHANUMERIC', '@fr_FR:Captcha numérique (addition)@en_US:Numerical captcha (add)@', 'Captcha'),
('QTY_CAPTCHANUMERICMINUS', '@fr_FR:Captcha numérique (soustraction)@en_US:Numerical captcha (sub)@', 'Captcha')");

$app->dbh->exec("INSERT INTO `DD_GABARIT` (`GAB_CODE`, `GAB_LIBELLE`, `GAB_PATH`, `GAB_CSS_PATH`, `GAB_PRINT_CSS_PATH`) VALUES
('GAB_DEFAULT', '@fr_FR:Initialisation@', 'include/gabarit_site/GAB_DEFAULT', 'include/css/GAB_DEFAULT/default.less', 'include/css/GAB_DEFAULT/print.css')");

$app->dbh->exec("INSERT INTO `DD_GABARITIMAGE` (`GBI_CODE`, `GAB_CODE`, `GBI_LIBELLE`, `GBI_PATH`) VALUES
('GBI_DEFAULT', 'GAB_DEFAULT', '@fr_FR:défaut@', 'images/GBI_DEFAULT/')");

$app->dbh->exec("INSERT INTO `DD_GABARITSTYLE` (`GBS_CODE`, `GAB_CODE`, `GBS_LIBELLE`, `GBS_PATH`, `GBS_EDITOR_PATH`) VALUES
('GBS_DEFAULT', 'GAB_DEFAULT', '@fr_FR:défaut@', '', 'include/css/GAB_DEFAULT/editor.css')");

$app->dbh->exec("INSERT INTO `DD_LANGUE` (`LNG_CODE`, `LNG_LIBELLE`, `LNG_FO`, `LNG_BO`) VALUES
('en_US', 'Anglais', 0, 0),
('fr_FR', 'Français', 1, 1)");

$app->dbh->exec("INSERT INTO `DD_LIAISON` (`LIA_CODE`, `LIA_LIBELLE`, `LIA_NOM_CHAMP_ID`, `LIA_LIBELLE_CHAMP`, `LIA_NOM_CHAMP`, `LIA_NOM_FICHIER`) VALUES
('COMMENTAIRE', '@fr_FR:Commentaires@', 'ID_COMMENTAIRE', '', '', ''),
('COMMENTAIRE_PARAM', '@fr_FR:Commentaires Paramétrage@', 'ID_COMMENTAIRE_PARAM', '', '@CPA_MES_DEPOT@CPA_SIGNATUREMAIL@', ''),
('OFF_PAGE', '@fr_FR:Page du site de contribution@', 'ID_PAGE', 'PAG_TITRE', '', ''),
('OFF_PARAGRAPHE', '@fr_FR:Paragraphe du site de test@en_US:Paragraphe du site de test@', 'ID_PARAGRAPHE', 'PAR_TITRE', '@PAR_CONTENU@', ''),
('ON_PAGE', '@fr_FR:Page du site public@', 'ID_PAGE', 'PAG_TITRE', '', ''),
('ON_PARAGRAPHE', '@fr_FR:Paragraphe du site public@en_US:Paragraphe du site public@', 'ID_PARAGRAPHE', 'PAR_TITRE', '@PAR_CONTENU@', ''),
('RECHERCHEREFERENCEMENT', '@fr_FR:Recherche DMK@', 'ID_RECHERCHEREFERENCEMENT', 'REC_TITLE', '@REC_DESCRIPTION@', '../cms/cms_rechercheReferencement.php'),
('REVISION_PAGE', '@fr_FR:Revision d''une page@en_US:Page revision@', 'ID_REVISIONPAGE', 'PAG_TITRE', '', ''),
('REVISION_PARAGRAPHE', '@fr_FR:Paragraphe d''une révision@en_US:Paragraphe d''une révision@', 'ID_REVISIONPARAGRAPHE', 'PAR_TITRE', '@PAR_CONTENU@', ''),
('WEBOTHEQUE', '@fr_FR:Description d''un élément de la webothèque@', 'ID_WEBOTHEQUE', 'WEB_LIBELLE', '@WEB_DESCRIPTION@', '')");

$app->dbh->exec("INSERT INTO `DD_MODULE` (`MOD_CODE`, `MOD_LIBELLE`, `MOD_GROUPE`, `MOD_OBLIGATOIRE`, `MOD_POIDS`) VALUES
('MOD_ABREVIATION', '@fr_FR:Abréviation@', '@fr_FR:Gestion de contenu@', 0, 15),
('MOD_ACCESSIBILITE', '@fr_FR:Accessibilité@', '@fr_FR:Administration@', 0, 16),
('MOD_CORE', '@fr_FR:Noyau@', '@fr_FR:Administration@', 1, 1),
('MOD_EXTRANET', '@fr_FR:Extranet@', '@fr_FR:Administration@', 0, 2),
('MOD_FORMULAIRE', '@fr_FR:Formulaires dynamiques@', '@fr_FR:Formulaires@', 0, 10),
('MOD_LANGUISME', '@fr_FR:Languisme@', '@fr_FR:Gestion de contenu@', 0, 12),
('MOD_RECHERCHE', '@fr_FR:Recherche@', '@fr_FR:Gestion de contenu@', 0, 13),
('MOD_REFERENCEMENT', '@fr_FR:Recherche DMK@', '@fr_FR:Gestion de contenu@', 0, 17),
('MOD_THEMATIQUE', '@fr_FR:Thématiques@', '@fr_FR:Gestion de contenu@', 0, 14),
('MOD_TRADUCTION', '@fr_FR:Traduction@', '@fr_FR:Gestion de contenu@', 0, 11),
('MOD_WEBOTHEQUE_DOCUMENT', '@fr_FR:Webothèque document@', '@fr_FR:Webothèque@', 0, 5),
('MOD_WEBOTHEQUE_FLASH', '@fr_FR:Webothèque flash@', '@fr_FR:Webothèque@', 0, 5),
('MOD_WEBOTHEQUE_IMAGE', '@fr_FR:Webothèque image@', '@fr_FR:Webothèque@', 0, 5),
('MOD_WEBOTHEQUE_LIENEXTERNE', '@fr_FR:Webothèque lien externe@', '@fr_FR:Webothèque@', 0, 5),
('MOD_WEBOTHEQUE_MUSIC', '@fr_FR:Webothèque musique@', '@fr_FR:Webothèque@', 0, 5),
('MOD_WEBOTHEQUE_VIDEO', '@fr_FR:Webothèque vidéo@', '@fr_FR:Webothèque@', 0, 5),
('MOD_WEBOTHEQUE_VIDEOEXTERNE', '@fr_FR:Webothèque vidéo externe@', '@fr_FR:Webothèque@', 0, 5),
('MOD_WEBOTHEQUE_WIDGET', '@fr_FR:Webothèque widget@', '@fr_FR:Webothèque@', 0, 5),
('MOD_ENSAVOIRPLUS', '@fr_FR:Blocs \‘En savoir plus\’ dans les paragraphes@', '@fr_FR:Administration@', 0, 19),
('MOD_COMMENTAIRE', '@fr_FR:Commentaires@', '@fr_FR:Gestion de contenu@', 0, 18)");

$app->dbh->exec("INSERT INTO `DD_EMAILTEMPLATE` (`EMT_CODE`, `MOD_CODE`, `EMT_DESCRIPTION`, `EMT_EXPEDITEUR`, `EMT_EXPEDITEURFROM`, `EMT_SUJET`, `EMT_BODYHTML`) VALUES
('EMT_FRM_NOTIF_BO', 'MOD_FORMULAIRE', 'Notification BO (l''expéditeur est celui défini dans le formulaire)', 'CMS', '', 'Formulaire [FRM_LIBELLE]', '<p>Le [DATE_JMA]</p>\r\n<p>Bonjour,<br />le formulaire \"[FRM_LIBELLE]\" a été renseigné :</p>\r\n<p>[REPONSES]</p>'),
('EMT_FRM_NOTIF_FO', 'MOD_FORMULAIRE', 'Notification FO (l''expéditeur est celui défini dans le formulaire)', 'CMS', '', 'AR : [FRM_LIBELLE]', '<p>Le [DATE_JMA]</p>\r\n<p>Bonjour,</p>\r\n<p>merci d''avoir rempli le formulaire \"[FRM_LIBELLE]\"</p>\r\n<p>[FRM_ACCUSERECEPTION]</p>'),
('EMT_EXTRANET_ACCOUNT_ACTIVATE', 'MOD_EXTRANET', 'Activation de compte', 'CMS', '', '[SIT_TITLE] : Activation de compte', '<p>Bonjour,</p><p>L\'administrateur du site \"[SIT_TITLE]\" a créé votre compte utilisateur.</p><p>Votre identifiant est : [UTI_LOGIN]</p><p>Pour activer votre compte et créer directement votre mot de passe, veuillez [LIEN_ACTIVATION].</p>
            <p>Attention ce lien n\'est valable que pendant 2 heures. Passé ce délai, vous devrez soumettre une nouvelle demande d\'activation de compte.</p>
            <p>Vous pouvez également contacter l\'administrateur de la plateforme pour lui demander de vous notifier pour recevoir une nouvelle demande d\'activation.</p>
            <p>[SIT_TITLE].</p>'),
('EMT_EXTRANET_ACCOUNT_FORGOTTEN', 'MOD_EXTRANET', 'Mot de passe perdu', 'CMS', '', '[SIT_TITLE] : Mot de passe perdu', '<p>Bonjour,</p><p>Pour récupérer vos informations d\'identification veuillez [LIEN_ACTIVATION]</p>
            <p>Attention ce lien n\'est valable que pendant 2 heures. Passé ce délai, vous devrez soumettre une nouvelle demande de modification de votre mot de passe.</p>
            <p>[SIT_TITLE].</p>'),
('EMT_COMMENTAIRE_VALIDE', 'MOD_COMMENTAIRE', 'Commentaire validé', 'CMS', '', '[SIT_TITLE] : Votre commentaire a été validé', '<p>Bonjour,</p>
            <p>Le commentaire que vous avez déposé sur notre site \"[LIEN_COMMENTAIRE]\" vient d\'être validé.</p>
            <p>[MESSAGE_VALIDATION_DU_SITE]</p>
            <p>[PARAMETRE_SIGNATURE_DU_SITE]</p>'),
('EMT_COMMENTAIRE_REFUS', 'MOD_COMMENTAIRE', 'Commentaire refusé', 'CMS', '', '[SIT_TITLE] : Votre commentaire a été refusé', '<p>Bonjour,</p>
            <p>Le commentaire que vous avez déposé sur notre site \"[LIEN_COMMENTAIRE]\" vient d\'être refusé..</p>
            <p>[MESSAGE_REFUS_DU_SITE]</p>
            <p>[PARAMETRE_SIGNATURE_DU_SITE]</p>'),
('EMT_COMMENTAIRE_NOUVEAU', 'MOD_COMMENTAIRE', 'Nouveau commentaire', 'CMS', '', '[SIT_TITLE] : Nouveau commentaire à modérer', '<p>Bonjour,</p>
            <p>Un nouveau commentaire (n°[NUMERO_COMMENTAIRE]) a été déposé sur la page \"[LIEN_PAGE_COMMENTEE]\" :</p>
            <ul>
                <li><strong>Pseudo :</strong>[PSEUDO]</li>
                <li><strong>E-mail :</strong>[EMAIL]</li>
                <li><strong>Message :</strong>[MESSAGE]</li>
            </ul>
            <p><strong>[LIEN_MODERATION]</strong></p>'),
('EMT_COMMENTAIRE_ABUS', 'MOD_COMMENTAIRE', 'Commentaire abusif signalé', 'CMS', '', '[SIT_TITLE] : Commentaire abusif signalé', '<p>Bonjour,</p>
            <p>Le commentaire (n°[NUMERO_COMMENTAIRE]) déposé sur la page  \"[INFO_PAGE_COMMENTEE]\" a été dénoncé par :</p>
            <ul>
                <li><strong>Prénom :</strong>[PRENOM]</li>
                <li><strong>E-mail :</strong>[EMAIL]</li>
                <li><strong>Commentaire dénoncé :</strong>[COMMENTAIRE]</li>
                <li><strong>Description de l\'abus :</strong>[DESCRIPTION_ABUS]</li>
            </ul>
            <p><strong>[LIEN_MODERATION]</strong></p>')");

$app->dbh->exec("INSERT INTO `DD_EMAILTEMPLATEKEY` (`EMT_CODE`, `EMK_LIBELLE`, `EMK_DESCRIPTION`) VALUES
('EMT_FRM_NOTIF_BO', 'FRM_LIBELLE', 'Libellé du formulaire'),
('EMT_FRM_NOTIF_BO', 'REPONSES', 'Ensemble des question / réponses'),
('EMT_FRM_NOTIF_FO', 'FRM_ACCUSERECEPTION', 'Texte d''accusé reception (lui même dynamique)'),
('EMT_FRM_NOTIF_FO', 'FRM_LIBELLE', 'Libellé du formulaire'),
('EMT_EXTRANET_ACCOUNT_ACTIVATE', 'UTI_CIVILITE', 'Civilité de l\'utilisateur'),
('EMT_EXTRANET_ACCOUNT_ACTIVATE', 'UTI_NOM', 'Nom de l\'utilisateur'),
('EMT_EXTRANET_ACCOUNT_ACTIVATE', 'UTI_PRENOM', 'Prénom de l\'utilisateur'),
('EMT_EXTRANET_ACCOUNT_ACTIVATE', 'UTI_LOGIN', 'Identifiant de l\'utilisateur'),
('EMT_EXTRANET_ACCOUNT_ACTIVATE', 'LIEN_ACTIVATION', 'Lien d\'activation de compte de la forme \"cliquer sur ce lien\"'),
('EMT_EXTRANET_ACCOUNT_FORGOTTEN', 'UTI_CIVILITE', 'Civilité de l\'utilisateur'),
('EMT_EXTRANET_ACCOUNT_FORGOTTEN', 'UTI_NOM', 'Nom de l\'utilisateur'),
('EMT_EXTRANET_ACCOUNT_FORGOTTEN', 'UTI_PRENOM', 'Prénom de l\'utilisateur'),
('EMT_EXTRANET_ACCOUNT_FORGOTTEN', 'UTI_LOGIN', 'Identifiant de l\'utilisateur'),
('EMT_EXTRANET_ACCOUNT_FORGOTTEN', 'LIEN_ACTIVATION', 'Lien de récupération des informations d\'identification de la forme \"cliquer sur ce lien\"'),
('EMT_COMMENTAIRE_VALIDE', 'LIEN_COMMENTAIRE', 'Lien vers le commentaire (le libellé du lien correspond au titre du site).'),
('EMT_COMMENTAIRE_VALIDE', 'MESSAGE_VALIDATION_DU_SITE', 'Message de validation des commentaires définit dans chacun des sites.'),
('EMT_COMMENTAIRE_VALIDE', 'PARAMETRE_SIGNATURE_DU_SITE', 'Signature de l\'emails associée aux commentaires définit pour chacun des sites.'),
('EMT_COMMENTAIRE_REFUS', 'LIEN_COMMENTAIRE', 'Lien vers le commentaire (le libellé du lien correspond au titre du site).'),
('EMT_COMMENTAIRE_REFUS', 'MESSAGE_REFUS_DU_SITE', 'Message de refus des commentaires définit dans chacun des sites.'),
('EMT_COMMENTAIRE_REFUS', 'PARAMETRE_SIGNATURE_DU_SITE', 'Signature de l\'emails associée aux commentaires définit pour chacun des sites.'),
('EMT_COMMENTAIRE_NOUVEAU', 'NUMERO_COMMENTAIRE', 'Numéro du commentaire.'),
('EMT_COMMENTAIRE_NOUVEAU', 'LIEN_PAGE_COMMENTEE', 'Lien vers la page où le commentaire a été déposé.'),
('EMT_COMMENTAIRE_NOUVEAU', 'PSEUDO', 'Pseudonyme de l\'utilisateur ayant déposé le commentaire.'),
('EMT_COMMENTAIRE_NOUVEAU', 'EMAIL', 'Adresse mail de l\'utilisateur ayant déposé le commentaire.'),
('EMT_COMMENTAIRE_NOUVEAU', 'MESSAGE', 'Contenu du commentaire.'),
('EMT_COMMENTAIRE_NOUVEAU', 'LIEN_MODERATION', 'Lien de modération du commentaire.'),
('EMT_COMMENTAIRE_ABUS', 'NUMERO_COMMENTAIRE', 'Numéro du commentaire.'),
('EMT_COMMENTAIRE_ABUS', 'INFO_PAGE_COMMENTEE', 'Titre et numéro de la page où le commentaire a été déposé.'),
('EMT_COMMENTAIRE_ABUS', 'PRENOM', 'Prénom de l\'utilisateur ayant signalé l\'abus.'),
('EMT_COMMENTAIRE_ABUS', 'EMAIL', 'Adresse mail de l\'utilisateur ayant signalé l\'abus.'),
('EMT_COMMENTAIRE_ABUS', 'COMMENTAIRE', 'Commentaire faisant l\'objet d\'un signalement.'),
('EMT_COMMENTAIRE_ABUS', 'DESCRIPTION_ABUS', 'Description du signalement.'),
('EMT_COMMENTAIRE_ABUS', 'LIEN_MODERATION', 'Lien de modération du commentaire.')");

$app->dbh->exec("INSERT INTO `DD_PAGESPECIALE` (`PGS_CODE`, `MOD_CODE`, `PGS_LIBELLE`) VALUES
('PGS_403', 'MOD_CORE', '@fr_FR:Page 403@en_US:403 Page@'),
('PGS_404', 'MOD_CORE', '@fr_FR:Page 404@en_US:404 Page@'),
('PGS_ACCESSIBILITE', 'MOD_ACCESSIBILITE', '@fr_FR:Accessibilité@en_US:Accessibility@'),
('PGS_AUTHENTIFICATION', 'MOD_EXTRANET', '@fr_FR:Authentification@en_US:Authentification@'),
('PGS_RECHERCHE', 'MOD_RECHERCHE', '@fr_FR:Recherche@en_US:Search@'),
('PGS_FORMULAIREABUS', 'MOD_COMMENTAIRE', '@fr_FR:Page Formulaire abus@en_US:Report abuse form Page@')");

$app->dbh->exec("INSERT INTO `DD_PAGESTATUT` (`PST_CODE`, `PST_LIBELLE`, `PST_POIDS`) VALUES
('PST_AREDIGER', '@fr_FR:A rédiger@en_US:Draft@', 1),
('PST_ATTENTEENLIGNE', '@fr_FR:Attente mise en ligne@en_US:To be published@', 3),
('PST_AVALIDER', '@fr_FR:A valider@en_US:To be validated@', 2),
('PST_ENLIGNE', '@fr_FR:Mise en ligne@en_US:Online@', 4),
('PST_HORSLIGNE', '@fr_FR:Hors ligne@en_US:Offline@', 5)");

$app->dbh->exec("INSERT INTO `DD_PARAGRAPHETYPE` (`PRT_CODE`, `PRT_LIBELLE`, `PRT_COLONNE`, `PRT_POIDS`) VALUES
('PRT_APPLIEXTERNE', '@fr_FR:Application externe@en_US:External application@', '@PAR_CENTRAL@', 8),
('PRT_COPIE', '@fr_FR:Copie de paragraphe@en_US:Copy@', '@PAR_LEFT@PAR_CENTRAL@PAR_RIGHT@', 3),
('PRT_FORMULAIRE', '@fr_FR:Formulaire dynamique@en_US:Computed form@', '@PAR_CENTRAL@', 7),
('PRT_HAUTDEPAGE', '@fr_FR:Haut de page@en_US:Top of page@', '@PAR_CENTRAL@', 5),
('PRT_PARTAGE', '@fr_FR:Partage de paragraphe@en_US:Shared Text@', '@PAR_LEFT@PAR_CENTRAL@PAR_RIGHT@', 4),
('PRT_SOMMAIRE', '@fr_FR:Sommaire de page@en_US:Summary@', '@PAR_LEFT@PAR_CENTRAL@PAR_RIGHT@', 6),
('PRT_TPL', '@fr_FR:Template@en_US:Template@', '@PAR_LEFT@PAR_CENTRAL@PAR_RIGHT@', 2),
('PRT_TXT', '@fr_FR:Paragraphe rédactionnel@en_US:Text@', '@PAR_LEFT@PAR_CENTRAL@PAR_RIGHT@', 1),
('PRT_WIDGET', '@fr_FR:Widget@en_US:Widget@', '@PAR_LEFT@PAR_CENTRAL@PAR_RIGHT@', 9)");

$app->dbh->exec("INSERT INTO `DD_PROFIL` (`PRO_CODE`, `PRO_LIBELLE`, `PRO_PAGE`) VALUES
('PRO_ABREVIATION', '@fr_FR:Gestionnaire abréviation@en_US:Abbrevation manager@', 0),
('PRO_FORMGEST', '@fr_FR:Gestionnaire formulaire@en_US:Form manager@', 0),
('PRO_FORMLECT', '@fr_FR:Lecteur formulaire@en_US:Form reader@', 0),
('PRO_LANGUISME', '@fr_FR:Gestionnaire languisme@en_US:Languism manager@', 0),
('PRO_RECHERCHE', '@fr_FR:Gestionnaire recherche@en_US:Search manager@', 0),
('PRO_REFERENCEMENT', '@fr_FR:Gestionnaire recherche DMK@en_US:DMK Search manager@', '0'),
('PRO_REDACTEUR', '@fr_FR:Rédacteur@en_US:Drafter@', 1),
('PRO_REFERENCEUR', '@fr_FR:Référenceur@en_US:S.E.O@', 1),
('PRO_ROOT', '@fr_FR:Super administrateur@en_US:System root@', 0),
('PRO_ROOT_SITE', '@fr_FR:Administrateur site@en_US:Website root@', 0),
('PRO_TEMPLATE', '@fr_FR:Gestionnaire template@en_US:Template manager@', 0),
('PRO_THEMATIQUE', '@fr_FR:Gestionnaire thématiques@en_US:Theme manager@', 0),
('PRO_TRADUCTION', '@fr_FR:Gestionnaire traduction@en_US:Translation manager@', 0),
('PRO_VALIDATEUR', '@fr_FR:Validateur@en_US:Validator@', 1),
('PRO_WEBDOCUMENT', '@fr_FR:Gestionnaire document@en_US:Document manager@', 0),
('PRO_WEBFLASH', '@fr_FR:Gestionnaire flash@en_US:Flash manager@', 0),
('PRO_WEBIMAGE', '@fr_FR:Gestionnaire image@en_US:Picture manager@', 0),
('PRO_WEBLIENEXTERNE', '@fr_FR:Gestionnaire lien@en_US:Link manager@', 0),
('PRO_WEBMUSIC', '@fr_FR:Gestionnaire audio@en_US:Audio manager@', 0),
('PRO_WEBROOT', '@fr_FR:Responsable webothèque@en_US:Web Bank manager@', 0),
('PRO_WEBVIDEO', '@fr_FR:Gestionnaire vidéo@en_US:Video manager@', 0),
('PRO_WEBVIDEOEXTERNE', '@fr_FR:Gestionnaire vidéo externe@en_US:External video manager@', 0),
('PRO_WEBWIDGET', '@fr_FR:Gestionnaire widget@en_US:Widget manager@', 0),
('PRO_COMMENTAIRE', '@fr_FR:Modérateur Pages@en_US:Moderator for page(Comments)@', 0)");

$app->dbh->exec("INSERT INTO `DD_SITE` (`SIT_CODE`, `GAB_CODE`, `GBS_CODE`, `GBI_CODE`, `LNG_CODE`, `SIT_LIBELLE`, `SIT_TITLE`, `SIT_RECHERCHE`, `SIT_HOST`, `SIT_EMAIL`, `SIT_SUPPORTKEY`, `SIT_RSS_ACTU`, `SIT_LOGO`, `SIT_FAVICON`, `SIT_GA_TAG`, `SIT_GA_ID`, `SIT_GA_KEYFILE`, `SIT_GA_ID_SITE`, `SIT_RSS_WEBMARKET`) VALUES
 (" . $app->dbh->quote($SIT_CODE) . ", 'GAB_DEFAULT', 'GBS_DEFAULT', 'GBI_DEFAULT', 'fr_FR', " . $app->dbh->quote($SIT_LIBELLE) . ", " . $app->dbh->quote($SIT_LIBELLE) . ", '', " . $app->dbh->quote($_SERVER['HTTP_HOST']) . ", " . $app->dbh->quote(EMAIL_FROM) . ", '', '', '', '', '', '', '', '', '')");

$app->dbh->exec("INSERT INTO `DD_TEMPLATE` (`TPL_CODE`, `MOD_CODE`, `TPL_LIBELLE`, `TPL_PAGE`, `TPL_AFFECTABLE`, `TPL_LINKABLE`, `TPL_COLONNE`, `TPL_POPUP_RESTRICTION`, `TPL_PARAMETRAGE`, `TPL_PARAMETRAGE_CLES`, `TPL_URLCODE`, `PGS_CODE`, `TPL_REWRITEURL`, `TPL_REWRITEMETHOD`) VALUES
('TPL_APPLIEXTERNE', 'MOD_CORE', '@fr_FR:Applications externes@en_US:External applications@', 'core.tpl_appliExterne.php', 0, 0, '@PAR_CENTRAL@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_COMMENTAIREFABUS', 'MOD_COMMENTAIRE', '@fr_FR:Formulaire Abus@en_US:Report Abuse Form@', 'core.tpl_commentaireFormulaireAbus.php', 0, 0, '@PAR_CENTRAL@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_FORMULAIRE', 'MOD_FORMULAIRE', '@fr_FR:Formulaires dynamiques@en_US:Forms@', 'core.tpl_formulaire.php', 0, 0, '@PAR_CENTRAL@', '', '', '@[LIBELLE]:Libellé du formulaire@', NULL, NULL, NULL, NULL),
('TPL_HERITAGE', 'MOD_CORE', 'Héritage', 'core.tpl_heritage.php', 0, 0, '@PAR_LEFT@PAR_CENTRAL@PAR_RIGHT@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_LISTEPAGES', 'MOD_CORE', '@fr_FR:Accroche de pages@en_US:List of pages@', 'core.tpl_accrochePages.php', 1, 0, '@PAR_CENTRAL@', 'cms/cms_choisirLienInternePopup.php?IDENTIFIANT=PAR_TPL_IDENTIFIANT&CONCATENATION=1&NOCLOSE=1', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_LISTEPAGESFILLE', 'MOD_CORE', '@fr_FR:Accroche de pages filles@en_US:List of child pages@', 'core.tpl_accrochePagesFilles.php', 1, 0, '@PAR_CENTRAL@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_LOGIN', 'MOD_EXTRANET', '@fr_FR:Authentification@en_US:Authentification@', 'core.tpl_login.php', 1, 1, '@PAR_CENTRAL@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_LOGIN_MDL', 'MOD_EXTRANET', '@fr_FR:Authentification@en_US:Authentification@', 'core.tpl_loginMDL.php', 1, 0, '@PAR_LEFT@PAR_RIGHT@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_LONGDESC', 'MOD_ACCESSIBILITE', '@fr_FR:Description longue d''une image@en_US:Longdesc (picture)@', 'core.tpl_longdesc.php', 0, 1, '@PAR_CENTRAL@', 'webotheque/web_choisirPopup.php?WBT_CODE=WBT_IMAGE&amp;amp;IDENTIFIANT=PAR_TPL_IDENTIFIANT', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_PARTAGE', 'MOD_CORE', 'Partage', 'core.tpl_partage.php', 0, 0, '@PAR_LEFT@PAR_CENTRAL@PAR_RIGHT@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_PLANSITE', 'MOD_CORE', '@fr_FR:Plan de site@en_US:Site Map@', 'core.tpl_planSite.php', 1, 0, '@PAR_CENTRAL@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_RECHERCHE', 'MOD_RECHERCHE', '@fr_FR:Résultat de recherche@en_US:Search result@', 'core.tpl_recherche.php', 1, 0, '@PAR_CENTRAL@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_RECHERCHEREF', 'MOD_REFERENCEMENT', '@fr_FR:Résultat de recherche@en_US:Search result@', 'core.tpl_rechercheReferencement.php', 1, 0, '@PAR_CENTRAL@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_SOMMAIREPAGE', 'MOD_CORE', 'Sommaire de page', 'core.tpl_sommairePage.php', 0, 0, '@PAR_CENTRAL@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_TAGCLOUD', 'MOD_CORE', '@fr_FR:Nuage de tags@en_US:Tag cloud@', 'core.tpl_tagCloud.php', 1, 0, '@PAR_LEFT@PAR_RIGHT@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_TAGLISTE', 'MOD_CORE', '@fr_FR:Résultat de recherche tags@en_US:Tag list result@', 'core.tpl_tagListe.php', 0, 0, '@PAR_CENTRAL@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_THEMATIQUE', 'MOD_THEMATIQUE', '@fr_FR:Fiche thématiques@en_US:Themes@', 'core.tpl_thematique.php', 0, 0, '@PAR_CENTRAL@', '', NULL, NULL, NULL, NULL, NULL, NULL),
('TPL_THEMATIQUELISTE', 'MOD_THEMATIQUE', '@fr_FR:Liste des thématiques@en_US:List of themes@', 'core.tpl_thematiqueListe.php', 1, 0, '@PAR_CENTRAL@PAR_LEFT@PAR_RIGHT@', '', NULL, NULL, NULL, NULL, NULL, NULL);");

$app->dbh->exec("INSERT INTO `DD_TRADUCTION` (`TRA_CODE`, `MOD_CODE`, `TRA_DESCRIPTION`, `TRA_MULTILIGNE`) VALUES
('cor_le_champ_X_n_est_pas_une_date_valide', 'MOD_CORE', 'Formulaire : Champ date non valide (utiliser %s)', 0),
('cor_le_champ_X_n_est_pas_un_captcha_valide', 'MOD_CORE', 'Formulaire : Captcha non valide (utiliser %s)', 0),
('cor_le_champ_X_n_est_pas_un_reel_valide', 'MOD_CORE', 'Formulaire : Champ réel non valide (utiliser %s)', 0),
('cor_le_champ_X_n_est_pas_un_entier_valide', 'MOD_CORE', 'Formulaire : Champ entier non valide (utiliser %s)', 0),
('cor_le_champ_X_n_est_pas_un_email_valide', 'MOD_CORE', 'Formulaire : Champ email non valide (utiliser %s)', 0),
('cor_le_champ_X_doit_etre_renseigne', 'MOD_CORE', 'Formulaire : Champ à renseigner (utiliser %s)', 0),
('web_voir_en_grand', 'MOD_WEBOTHEQUE_IMAGE', 'Texte d\'information sur l\'ouverture de l\'image en lightbox (loupe)', 0),
('Accuse_reception', 'MOD_FORMULAIRE', '', 0),
('Action', 'MOD_EXTRANET', '', 0),
('Aucun_fichier', 'MOD_FORMULAIRE', '', 0),
('Aucun_resultat', 'MOD_RECHERCHE', '', 0),
('champs_obligatoire', 'MOD_FORMULAIRE', '', 0),
('texte_alternatif_aide', 'MOD_FORMULAIRE', 'Texte alternatif du bouton d''aide', 0),
('Consulter_derniere_page', 'MOD_RECHERCHE', '', 0),
('Consulter_page_X', 'MOD_RECHERCHE', '', 0),
('Consulter_premiere_page', 'MOD_RECHERCHE', '', 0),
('Contribuer', 'MOD_EXTRANET', '', 0),
('Deconnexion', 'MOD_EXTRANET', '', 0),
('Derniere', 'MOD_RECHERCHE', '', 0),
('Erreur_authentification', 'MOD_EXTRANET', '', 0),
('erreur_traitement', 'MOD_FORMULAIRE', '', 0),
('Extension_incorrecte', 'MOD_FORMULAIRE', '', 0),
('for_texte_taille_max_upload', 'MOD_FORMULAIRE', 'Taille maximale de fichier', 0),
('for_fichier_trop_volumineux', 'MOD_FORMULAIRE', 'Erreur : fichier trop volumineux', 0),
('Login', 'MOD_EXTRANET', '', 0),
('login_mdp_oublie', 'MOD_EXTRANET', 'Lien vers la fonctionnalité \"Mot de passe perdu\"', 0),
('mention_cnil', 'MOD_FORMULAIRE', '', 0),
('Message_remerciements_defaut', 'MOD_FORMULAIRE', '', 0),
('Numero_dossier', 'MOD_FORMULAIRE', '', 0),
('Page', 'MOD_RECHERCHE', '', 0),
('Password', 'MOD_EXTRANET', '', 0),
('Piece_jointe', 'MOD_FORMULAIRE', '', 0),
('Premiere', 'MOD_RECHERCHE', '', 0),
('resultat_sur', 'MOD_RECHERCHE', '', 0),
('resultats_sur', 'MOD_RECHERCHE', '', 0),
('Retour_formulaire', 'MOD_FORMULAIRE', '', 0),
('Titre', 'MOD_EXTRANET', '', 0),
('Tri_ascendant_sur_X', 'MOD_RECHERCHE', '', 0),
('Tri_descendant_sur_X', 'MOD_RECHERCHE', '', 0),
('rechercher', 'MOD_RECHERCHE', '', 0),
('com_je_reagis', 'MOD_COMMENTAIRE', 'Libellé du lien pour afficher le formulaire de depôt de commentaire', 0),
('com_commentaire', 'MOD_COMMENTAIRE', 'Libellé du lien (1 xxxxx) pour afficher la liste des commentaires si un seul résultat', 0),
('com_commentaires', 'MOD_COMMENTAIRE', 'Libellé du lien (X xxxxx) pour afficher la liste des commentaires si plus d''un résultat', 0),
('com_commentaires_voir', 'MOD_COMMENTAIRE', 'Libellé lors du hover sur le lien pour afficher la liste des commentaires', 0),
('com_commentaire_a_ete_valide', 'MOD_COMMENTAIRE', 'Sujet du mail de notification après validation d''un commentaire', 0),
('com_commentaire_a_ete_refuse', 'MOD_COMMENTAIRE', 'Sujet du mail de notification après refus d''un commentaire', 0),
('com_monpseudo', 'MOD_COMMENTAIRE', 'Libellé du champ <Mon pseudo>', 0),
('com_monemail', 'MOD_COMMENTAIRE', 'Libellé du champ <Mon e-mail>', 0),
('com_moncommentaire', 'MOD_COMMENTAIRE', 'Libellé du champ <Mon Commentaire>', 0),
('com_message_abus', 'MOD_COMMENTAIRE', 'Libellé pour signaler un abus', 0),
('com_message_abus_recu', 'MOD_COMMENTAIRE', 'Message affiché après l''envoi du formulaire Abus', 0),
('com_btn_envoyer', 'MOD_COMMENTAIRE', 'Bouton de soumission du formulaire', 0),
('com_retour_page', 'MOD_COMMENTAIRE', 'Libellé du lien de retour vers la page des commentaires', 0),
('com_moncommentaire_info', 'MOD_COMMENTAIRE', 'Message info pour le champ <Mon Commentaire>', 0),
('com_moncommentaire_nombre', 'MOD_COMMENTAIRE', 'Label pour le nombre de caractères du champ <Mon Commentaire>', 0),
('com_commentaire_abus_titre', 'MOD_COMMENTAIRE', 'Titre du formulaire pour la saisie d''une alerte pour un abus', 0),
('com_commentaire_par', 'MOD_COMMENTAIRE', '', 0),
('com_commentaire_le', 'MOD_COMMENTAIRE', '', 0),
('com_monform', 'MOD_COMMENTAIRE', 'Titre du formulaire pour le depot d''un commentaire', 0),
('com_form_repere', 'MOD_COMMENTAIRE', 'Libellé du champ <Commentaire repéré>', 0),
('com_form_decrireabus', 'MOD_COMMENTAIRE', 'Libellé du champ <Décrire l''abus>', 0),
('com_fe_pseudo', 'MOD_COMMENTAIRE', 'Libellé message erreur pseudo requis', 0),
('com_fe_mail', 'MOD_COMMENTAIRE', 'Libellé message erreur mail requis', 0),
('com_fe_mail_invalid', 'MOD_COMMENTAIRE', 'Libellé message erreur mail invalid', 0),
('com_fe_message', 'MOD_COMMENTAIRE', 'Libellé message erreur message requis', 0),
('com_afe_prenom', 'MOD_COMMENTAIRE', 'Libellé message erreur abus prénom requis', 0),
('com_afe_mail', 'MOD_COMMENTAIRE', 'Libellé message erreur abus mail requis', 0),
('com_afe_mail_invalid', 'MOD_COMMENTAIRE', 'Libellé message erreur abus mail invalid', 0),
('com_afe_decrireabus', 'MOD_COMMENTAIRE', 'Libellé message erreur abus message requis', 0),
('com_form_prenom', 'MOD_COMMENTAIRE', 'Libellé du champ <Mon prénom>', 0),
('com_form_submitError', 'MOD_COMMENTAIRE', 'Message erreur à la sauvegarde d''un abus', 0),
('com_form_abuscom', 'MOD_COMMENTAIRE', 'Message erreur si l''abus est associé à aucun commentaire', 0),
('esp_En_Savoir_Plus', 'MOD_ENSAVOIRPLUS', 'Libellé du lien (En savoir plus)', 0),
('esp_Document', 'MOD_ENSAVOIRPLUS', '', 0),
('esp_a_telecharger', 'MOD_ENSAVOIRPLUS', '', 0),
('esp_nouvelle_fenetre', 'MOD_ENSAVOIRPLUS', '', 0),
('cnil_lien_savoir_plus', 'MOD_CORE', 'Marqueur GA conforme CNIL : Libellé du lien permettant d\'afficher les détails au sein d\'une fenêtre modale', 0),
('cnil_titre_popup', 'MOD_CORE', 'Marqueur GA conforme CNIL : Titre de la fenêtre modale', 0),
('cnil_contenu_popup', 'MOD_CORE', 'Marqueur GA conforme CNIL : Informations CNIL présentées au sein de la fenêtre modale', 1),
('cnil_btn_popup_opposer', 'MOD_CORE', 'Marqueur GA conforme CNIL : Libellé du bouton de refus', 0),
('cnil_btn_popup_accepter', 'MOD_CORE', 'Marqueur GA conforme CNIL : Libellé du bouton d\'acceptation', 0),
('cnil_btn_popup_close', 'MOD_CORE', 'Marqueur GA conforme CNIL : Libelle du lien de fermeture de la fenêtre modale', 0),
('cnil_txt_bandeau_cnil', 'MOD_CORE', 'Marqueur GA conforme CNIL : Contenu du bandeau d\'information', 1),
('cnil_txt_bandeau_cnil_refus', 'MOD_CORE', 'Marqueur GA conforme CNIL : Contenu du bandeau d\'information après un refus', 1)
");

$app->dbh->exec("INSERT INTO `DD_WEBOTHEQUETYPE` (`WBT_CODE`, `WBT_LIBELLE`) VALUES
('WBT_DOCUMENT', '@fr_FR:Document@en_US:Document@'),
('WBT_FLASH', '@fr_FR:Flash@en_US:Flash@'),
('WBT_IMAGE', '@fr_FR:Image@en_US:Picture@'),
('WBT_LIENEXTERNE', '@fr_FR:Lien externe@en_US:External link@'),
('WBT_MUSIC', '@fr_FR:Audio@en_US:Audio@'),
('WBT_VIDEO', '@fr_FR:Vidéo@en_US:Video@'),
('WBT_VIDEOEXTERNE', '@fr_FR:Vidéo externe@en_US:External video@'),
('WBT_WIDGET', '@fr_FR:Widget@en_US:Widget@')");

$app->dbh->exec("INSERT INTO `MODULE_PROFIL` (`MOD_CODE`, `PRO_CODE`) VALUES
('MOD_ABREVIATION', 'PRO_ABREVIATION'),
('MOD_FORMULAIRE', 'PRO_FORMGEST'),
('MOD_FORMULAIRE', 'PRO_FORMLECT'),
('MOD_LANGUISME', 'PRO_LANGUISME'),
('MOD_RECHERCHE', 'PRO_RECHERCHE'),
('MOD_REFERENCEMENT', 'PRO_REFERENCEMENT'),
('MOD_CORE', 'PRO_REDACTEUR'),
('MOD_CORE', 'PRO_REFERENCEUR'),
('MOD_CORE', 'PRO_ROOT'),
('MOD_CORE', 'PRO_ROOT_SITE'),
('MOD_THEMATIQUE', 'PRO_THEMATIQUE'),
('MOD_TRADUCTION', 'PRO_TRADUCTION'),
('MOD_CORE', 'PRO_VALIDATEUR'),
('MOD_WEBOTHEQUE_DOCUMENT', 'PRO_WEBDOCUMENT'),
('MOD_WEBOTHEQUE_FLASH', 'PRO_WEBFLASH'),
('MOD_WEBOTHEQUE_IMAGE', 'PRO_WEBIMAGE'),
('MOD_WEBOTHEQUE_LIENEXTERNE', 'PRO_WEBLIENEXTERNE'),
('MOD_WEBOTHEQUE_MUSIC', 'PRO_WEBMUSIC'),
('MOD_WEBOTHEQUE_DOCUMENT', 'PRO_WEBROOT'),
('MOD_WEBOTHEQUE_FLASH', 'PRO_WEBROOT'),
('MOD_WEBOTHEQUE_IMAGE', 'PRO_WEBROOT'),
('MOD_WEBOTHEQUE_LIENEXTERNE', 'PRO_WEBROOT'),
('MOD_WEBOTHEQUE_MUSIC', 'PRO_WEBROOT'),
('MOD_WEBOTHEQUE_VIDEO', 'PRO_WEBROOT'),
('MOD_WEBOTHEQUE_VIDEOEXTERNE', 'PRO_WEBROOT'),
('MOD_WEBOTHEQUE_VIDEO', 'PRO_WEBVIDEO'),
('MOD_WEBOTHEQUE_VIDEOEXTERNE', 'PRO_WEBVIDEOEXTERNE'),
('MOD_WEBOTHEQUE_WIDGET', 'PRO_WEBWIDGET'),
('MOD_WEBOTHEQUE_WIDGET', 'PRO_WEBROOT'),
('MOD_COMMENTAIRE', 'PRO_COMMENTAIRE')
");

$app->dbh->exec("INSERT INTO `SITE_MODULE` (`SIT_CODE`, `MOD_CODE`) VALUES
(" . $app->dbh->quote($SIT_CODE) . ", 'MOD_CORE')");

$app->dbh->exec("INSERT INTO `STOPWORD_LANGUE` (`STP_LIBELLE`, `LNG_CODE`) VALUES
('abord', 'fr_FR'),
('alors', 'fr_FR'),
('aucun', 'fr_FR'),
('aussi', 'fr_FR'),
('autre', 'fr_FR'),
('avant', 'fr_FR'),
('avec', 'fr_FR'),
('avoir', 'fr_FR'),
('bon', 'fr_FR'),
('car', 'fr_FR'),
('cela', 'fr_FR'),
('certain', 'fr_FR'),
('ces', 'fr_FR'),
('ceux', 'fr_FR'),
('chaque', 'fr_FR'),
('comme', 'fr_FR'),
('comment', 'fr_FR'),
('dans', 'fr_FR'),
('debut', 'fr_FR'),
('dedans', 'fr_FR'),
('dehors', 'fr_FR'),
('depuis', 'fr_FR'),
('des', 'fr_FR'),
('deux', 'fr_FR'),
('devrait', 'fr_FR'),
('doit', 'fr_FR'),
('donc', 'fr_FR'),
('dos', 'fr_FR'),
('droite', 'fr_FR'),
('elle', 'fr_FR'),
('elles', 'fr_FR'),
('encore', 'fr_FR'),
('essai', 'fr_FR'),
('est', 'fr_FR'),
('etaient', 'fr_FR'),
('etat', 'fr_FR'),
('ete', 'fr_FR'),
('etions', 'fr_FR'),
('etre', 'fr_FR'),
('fait', 'fr_FR'),
('faites', 'fr_FR'),
('fois', 'fr_FR'),
('font', 'fr_FR'),
('force', 'fr_FR'),
('haut', 'fr_FR'),
('hors', 'fr_FR'),
('ici', 'fr_FR'),
('ils', 'fr_FR'),
('juste', 'fr_FR'),
('les', 'fr_FR'),
('leur', 'fr_FR'),
('maintenant', 'fr_FR'),
('mais', 'fr_FR'),
('meme', 'fr_FR'),
('mes', 'fr_FR'),
('mine', 'fr_FR'),
('moins', 'fr_FR'),
('mon', 'fr_FR'),
('mot', 'fr_FR'),
('notre', 'fr_FR'),
('nous', 'fr_FR'),
('nouveaux', 'fr_FR'),
('par', 'fr_FR'),
('parce', 'fr_FR'),
('parole', 'fr_FR'),
('pas', 'fr_FR'),
('peu', 'fr_FR'),
('peut', 'fr_FR'),
('plupart', 'fr_FR'),
('plus', 'fr_FR'),
('point', 'fr_FR'),
('pour', 'fr_FR'),
('pourquoi', 'fr_FR'),
('quand', 'fr_FR'),
('que', 'fr_FR'),
('quel', 'fr_FR'),
('quelle', 'fr_FR'),
('quelles', 'fr_FR'),
('quels', 'fr_FR'),
('qui', 'fr_FR'),
('sans', 'fr_FR'),
('ses', 'fr_FR'),
('seulement', 'fr_FR'),
('sien', 'fr_FR'),
('son', 'fr_FR'),
('sont', 'fr_FR'),
('sous', 'fr_FR'),
('soyez', 'fr_FR'),
('sujet', 'fr_FR'),
('sur', 'fr_FR'),
('tandis', 'fr_FR'),
('tellement', 'fr_FR'),
('tels', 'fr_FR'),
('tes', 'fr_FR'),
('ton', 'fr_FR'),
('tous', 'fr_FR'),
('tout', 'fr_FR'),
('tres', 'fr_FR'),
('trop', 'fr_FR'),
('valeur', 'fr_FR'),
('voie', 'fr_FR'),
('voient', 'fr_FR'),
('vont', 'fr_FR'),
('votre', 'fr_FR'),
('vous', 'fr_FR');
");

$app->dbh->exec("INSERT INTO `TRADUCTION_LANGUE` (`TRA_CODE`, `LNG_CODE`, `TRA_LIBELLE`) VALUES
('login_mdp_oublie', 'fr_FR', 'Mot de passe perdu ?'),
('login_mdp_oublie', 'en_US', 'Forgot password?'),
('cor_le_champ_X_n_est_pas_une_date_valide', 'fr_FR', 'Le champ %s n''est pas une date valide.'),
('cor_le_champ_X_n_est_pas_un_reel_valide', 'fr_FR', 'Le champ %s n''est pas un réel valide.'),
('cor_le_champ_X_n_est_pas_un_entier_valide', 'fr_FR', 'Le champ %s n''est pas un entier valide.'),
('cor_le_champ_X_n_est_pas_un_email_valide', 'fr_FR', 'Le champ %s n''est pas un email valide.'),
('cor_le_champ_X_n_est_pas_un_captcha_valide', 'fr_FR', 'Le champ %s n''est pas valide.'),
('cor_le_champ_X_doit_etre_renseigne', 'fr_FR','Le champ %s doit être renseigné.'),
('web_voir_en_grand', 'fr_FR', 'Voir l''image en grand'),
('web_voir_en_grand', 'en_US', 'Enlarge the picture'),
('Accuse_reception', 'en_US', ''),
('Accuse_reception', 'fr_FR', 'Accusé de réception'),
('Action', 'en_US', 'Go'),
('Action', 'fr_FR', 'S''authentifier'),
('Aucun_fichier', 'en_US', ''),
('Aucun_fichier', 'fr_FR', 'Aucun fichier'),
('Aucun_resultat', 'en_US', 'No result'),
('Aucun_resultat', 'fr_FR', 'Aucun résultat'),
('champs_obligatoire', 'en_US', '* Mandatory fields'),
('champs_obligatoire', 'fr_FR', '* Champs obligatoires'),
('Consulter_derniere_page', 'en_US', 'See last page of results'),
('Consulter_derniere_page', 'fr_FR', 'Consulter la dernière page des résultats'),
('Consulter_page_X', 'en_US', 'See page %d of results'),
('Consulter_page_X', 'fr_FR', 'Consulter la page %d des résultats'),
('Consulter_premiere_page', 'en_US', 'See first page of results'),
('Consulter_premiere_page', 'fr_FR', 'Consulter la première page des résultats'),
('Contribuer', 'en_US', 'Contribute'),
('Contribuer', 'fr_FR', 'Contribuer'),
('Deconnexion', 'en_US', 'Deconnection'),
('Deconnexion', 'fr_FR', 'Se déconnecter'),
('Derniere', 'en_US', 'Last'),
('Derniere', 'fr_FR', 'Dernière'),
('Erreur_authentification', 'en_US', 'Error'),
('Erreur_authentification', 'fr_FR', 'Authentification impossible'),
('erreur_traitement', 'en_US', 'erreur_traitement'),
('erreur_traitement', 'fr_FR', 'Erreur de traitement'),
('Extension_incorrecte', 'en_US', 'Extension_incorrecte'),
('Extension_incorrecte', 'fr_FR', 'Extension incorrecte'),
('for_texte_taille_max_upload', 'fr_FR', '(Taille max. %s)'),
('for_texte_taille_max_upload', 'en_US', '(Max file size %s)'),
('for_fichier_trop_volumineux', 'fr_FR', 'Fichier trop volumineux'),
('for_fichier_trop_volumineux', 'en_US', 'File too big'),
('Login', 'en_US', 'Login'),
('Login', 'fr_FR', 'Identifiant'),
('mention_cnil', 'en_US', 'mention_cnil'),
('mention_cnil', 'fr_FR', 'Conformément à la loi Informatique et Libertés du 6 janvier 1978 réformée, vous disposez d''un droit d’accès, de modification, de rectification et de suppression des données vous concernant. Afin d''exercer ce droit nous vous invitons à nous contacter.'),
('Message_remerciements_defaut', 'en_US', 'Message_remerciements_defaut'),
('Message_remerciements_defaut', 'fr_FR', 'Votre demande a bien été transmise et sera traitée dans les plus brefs délais.'),
('Numero_dossier', 'en_US', 'Numero_dossier'),
('Numero_dossier', 'fr_FR', 'Numéro de dossier'),
('Page', 'en_US', 'Page'),
('Page', 'fr_FR', 'Page'),
('Password', 'en_US', 'Password'),
('Password', 'fr_FR', 'Mot de passe'),
('Piece_jointe', 'en_US', 'Piece_jointe'),
('Piece_jointe', 'fr_FR', 'en pièce jointe'),
('Premiere', 'en_US', 'First'),
('Premiere', 'fr_FR', 'Première '),
('resultat_sur', 'en_US', ' result on '),
('resultat_sur', 'fr_FR', ' résultat sur '),
('resultats_sur', 'en_US', ' results on '),
('resultats_sur', 'fr_FR', ' résultats sur '),
('Retour_formulaire', 'en_US', 'Retour_formulaire'),
('Retour_formulaire', 'fr_FR', 'Retour au formulaire'),
('texte_alternatif_aide', 'en_US', 'Help'),
('texte_alternatif_aide', 'fr_FR', 'Aide'),
('Titre', 'en_US', 'Authentification'),
('Titre', 'fr_FR', 'Authentification'),
('Tri_ascendant_sur_X', 'en_US', 'Sort in ascending order on %s'),
('Tri_ascendant_sur_X', 'fr_FR', 'Tri ascendant sur %s'),
('Tri_descendant_sur_X', 'en_US', 'Sort in descending order on %s'),
('Tri_descendant_sur_X', 'fr_FR', 'Tri descendant sur %s'),
('rechercher', 'fr_FR', 'Rechercher'),
('rechercher', 'en_US', 'Search'),
('com_je_reagis', 'fr_FR', 'Je réagis'),
('com_je_reagis', 'en_US', 'Comment'),
('com_commentaire', 'fr_FR', 'commentaire'),
('com_commentaire', 'en_US', 'comment'),
('com_commentaires', 'fr_FR', 'commentaires'),
('com_commentaires', 'en_US', 'comments'),
('com_commentaires_voir', 'fr_FR', 'Afficher les commentaires'),
('com_commentaires_voir', 'en_US', 'View the comments'),
('com_commentaire_a_ete_valide', 'fr_FR', 'Votre commentaire a été validé'),
('com_commentaire_a_ete_valide', 'en_US', 'Your comment has been validated'),
('com_commentaire_a_ete_refuse', 'fr_FR', 'Votre commentaire a été refusé'),
('com_commentaire_a_ete_refuse', 'en_US', 'Your comment has been refused'),
('com_monpseudo', 'fr_FR', 'Mon pseudo'),
('com_monpseudo', 'en_US', 'My alias'),
('com_monemail', 'fr_FR', 'Mon e-mail'),
('com_monemail', 'en_US', 'My email'),
('com_moncommentaire', 'fr_FR', 'Mon commentaire'),
('com_moncommentaire', 'en_US', 'My comment'),
('com_message_abus', 'fr_FR', 'Signaler un abus'),
('com_message_abus', 'en_US', 'Report this comment'),
('com_message_abus_recu', 'fr_FR', 'Nous vous remercions de nous avoir alerté et tâcherons de modérer ce commentaire dans les plus brefs délais.'),
('com_message_abus_recu', 'en_US', 'Thank you for your alert. We shall strive to moderate this comment as soon as possible.'),
('com_btn_envoyer', 'fr_FR', 'Envoyer'),
('com_btn_envoyer', 'en_US', 'Send'),
('com_retour_page', 'fr_FR', 'Retour à la page commentée'),
('com_retour_page', 'en_US', 'Back to page commented'),
('com_moncommentaire_info', 'fr_FR', 'Votre commentaire ne doit pas excéder 500 caractères sinon il sera tronqué.'),
('com_moncommentaire_info', 'en_US', 'If your comment exceeds 500 characters, it will be truncated.'),
('com_moncommentaire_nombre', 'fr_FR', 'Nombre de caractères utilisés'),
('com_moncommentaire_nombre', 'en_US', 'Number of characters used'),
('com_commentaire_abus_titre', 'fr_FR', 'Alerter les modérateurs'),
('com_commentaire_abus_titre', 'en_US', 'Report this comment'),
('com_commentaire_par', 'fr_FR', 'par'),
('com_commentaire_par', 'en_US', 'by'),
('com_commentaire_le', 'fr_FR', 'le'),
('com_commentaire_le', 'en_US', 'posted on'),
('com_monform', 'fr_FR', 'Ajouter un commentaire'),
('com_monform', 'en_US', 'Add a comment'),
('com_form_repere', 'fr_FR', 'Commentaire repéré'),
('com_form_repere', 'en_US', 'Reported comment'),
('com_form_decrireabus', 'fr_FR', 'Décrire l''abus'),
('com_form_decrireabus', 'en_US', 'Define abuse'),
('com_fe_pseudo', 'fr_FR', 'Le champ <Mon pseudo> est obligatoire.'),
('com_fe_pseudo', 'en_US', 'Field <My alias> is mandatory.'),
('com_fe_mail', 'fr_FR', 'Le champ <Mon e-mail> est obligatoire.'),
('com_fe_mail', 'en_US', 'Field <My email> is mandatory.'),
('com_fe_mail_invalid', 'fr_FR', 'La valeur du champ <Mon e-mail> est invalide.'),
('com_fe_mail_invalid', 'en_US', 'Invalid value for field <My email>.'),
('com_fe_message', 'fr_FR', 'Le champ <Mon commentaire> est obligatoire.'),
('com_fe_message', 'en_US', 'Field <My comment> is mandatory.'),
('com_afe_prenom', 'fr_FR', 'Le champ <Mon prénom> est obligatoire.'),
('com_afe_prenom', 'en_US', 'Field <My first name> is mandatory.'),
('com_afe_mail', 'fr_FR', 'Le champ <Mon e-mail> est obligatoire.'),
('com_afe_mail', 'en_US', 'Field <My email> is mandatory.'),
('com_afe_mail_invalid', 'fr_FR', 'La valeur du champ <Mon e-mail> est invalide.'),
('com_afe_mail_invalid', 'en_US', 'Invalid value for field <My email>.'),
('com_afe_decrireabus', 'fr_FR', 'Le champ <Décrire l''abus> est obligatoire.'),
('com_afe_decrireabus', 'en_US', 'Field <Define abuse> is mandatory.'),
('com_form_prenom', 'fr_FR', 'Mon prénom'),
('com_form_prenom', 'en_US', 'My first name'),
('com_form_submitError', 'fr_FR', 'Une erreur s''est produit à la sauvegarde de cet abus. Veuillez contacter l''administrateur du site.'),
('com_form_submitError', 'en_US', 'An error has occured. Please contact the site admin.'),
('com_form_abuscom', 'fr_FR', 'Nous ne retrouvons pas le commentaire lié.'),
('com_form_abuscom', 'en_US', 'Nous ne retrouvons pas le commentaire lié.'),
('esp_En_Savoir_Plus', 'fr_FR', 'En savoir plus'),
('esp_En_Savoir_Plus', 'en_US', 'More'),
('esp_Document', 'fr_FR', 'Document'),
('esp_Document', 'en_US', 'Document'),
('esp_a_telecharger', 'fr_FR', 'à télécharger'),
('esp_a_telecharger', 'en_US', 'download'),
('esp_nouvelle_fenetre', 'fr_FR', 'Nouvelle fenêtre'),
('esp_nouvelle_fenetre', 'en_US', 'New window'),
('cnil_lien_savoir_plus', 'fr_FR', 'En savoir plus ou s\'opposer'),
('cnil_titre_popup', 'fr_FR', 'Les cookies Google Analytics'),
('cnil_contenu_popup', 'fr_FR', 'Ce site utilise des cookies de Google Analytics, ces cookies nous aident à identifier le contenu qui vous interesse le plus ainsi qu\'à repérer certains dysfonctionnements. Vos données de navigations sur ce site sont envoyées à Google Inc'),
('cnil_btn_popup_opposer', 'fr_FR', 'S\'opposer'),
('cnil_btn_popup_accepter', 'fr_FR', 'Accepter'),
('cnil_btn_popup_close', 'fr_FR', 'Fermer'),
('cnil_txt_bandeau_cnil', 'fr_FR', 'Ce site utilise Google Analytics. En continuant à naviguer, vous nous autorisez à déposer un cookie à des fins de mesure d\'audience.'),
('cnil_txt_bandeau_cnil_refus', 'fr_FR', 'Vous vous êtes opposé au dépôt de cookies de mesures d\'audience dans votre navigateur.')
");

$app->dbh->exec("INSERT INTO `UTILISATEUR` (`ID_UTILISATEUR`, `SIT_CODE`, `LNG_CODE`, `ID_PAGE`, `UTI_CIVILITE`, `UTI_NOM`, `UTI_PRENOM`, `UTI_EMAIL`, `UTI_LOGIN`, `UTI_PASSWORD`, `UTI_FONCTION`, `UTI_TELEPHONE`, `UTI_ORGANISME`, `UTI_ADRESSE`, `UTI_CODEPOSTAL`, `UTI_VILLE`, `UTI_PAYS`, `UTI_FAX`, `UTI_DATECREATION`, `UTI_DATEMODIFICATION`, `UTI_LASTCONNEXION`) VALUES
(1, " . $app->dbh->quote($SIT_CODE) . ", 'fr_FR', NULL, " . $app->dbh->quote($UTI_CIVILITE) . ", ".$app->dbh->quote($UTI_NOM).", " . $app->dbh->quote($UTI_PRENOM) . ", " . $app->dbh->quote($UTI_EMAIL) . ", " . $app->dbh->quote($UTI_LOGIN) . ", '', '', '', '', '', '', '', '', '', NULL, unix_timestamp(), NULL)");

$app->dbh->exec("INSERT INTO `ROLE` (`ID_ROLE`, `SIT_CODE`, `ID_UTILISATEUR`, `PRO_CODE`, `ID_PAGE`) VALUES
(1, NULL, 1, 'PRO_ROOT', NULL)");

$app->dbh->exec("INSERT INTO `WORKFLOW` (`ID_WORKFLOW`, `PST_CODE_IN`, `PST_CODE_OUT`, `WKF_LIBELLE`, `WKF_PROFIL`, `WKF_POIDS`, `WKF_PRE_FONCTION`, `WKF_POST_FONCTION`, `WKF_CRONABLE`) VALUES
(1, 'PST_AREDIGER', 'PST_AVALIDER', '@fr_FR:Transmettre pour validation@en_US:Forward to validation@', '@PRO_REDACTEUR@PRO_VALIDATEUR@PRO_ROOT@PRO_ROOT_SITE@', 1, NULL, NULL, 0),
(2, 'PST_AREDIGER', 'PST_ATTENTEENLIGNE', '@fr_FR:Attendre la mise en ligne@en_US:Await publication@', '@PRO_VALIDATEUR@PRO_ROOT@PRO_ROOT_SITE@', 2, NULL, NULL, 0),
(3, 'PST_AVALIDER', 'PST_ATTENTEENLIGNE', '@fr_FR:Attendre la mise en ligne@en_US:Await publication@', '@PRO_VALIDATEUR@PRO_ROOT@PRO_ROOT_SITE@', 3, NULL, NULL, 0),
(4, 'PST_AVALIDER', 'PST_AREDIGER', '@fr_FR:Refuser la validation@en_US:Reject validation@', '@PRO_VALIDATEUR@PRO_ROOT@PRO_ROOT_SITE@', 1, NULL, NULL, 0),
(5, 'PST_ATTENTEENLIGNE', 'PST_AREDIGER', '@fr_FR:Renvoyer en rédaction@en_US:Return to edition@', '@PRO_REDACTEUR@PRO_VALIDATEUR@PRO_ROOT@PRO_ROOT_SITE@', 1, NULL, NULL, 0),
(6, 'PST_AVALIDER', 'PST_AREDIGER', '@fr_FR:Renvoyer en rédaction@en_US:Return to edition@', '@PRO_REDACTEUR@', 2, NULL, NULL, 0),
(7, 'PST_ATTENTEENLIGNE', 'PST_ENLIGNE', '@fr_FR:Mettre en ligne@en_US:Publish@', '@PRO_VALIDATEUR@PRO_ROOT@PRO_ROOT_SITE@', 2, 'pre_PST_ENLIGNE', 'post_PST_ENLIGNE', 1),
(8, 'PST_ENLIGNE', 'PST_AREDIGER', '@fr_FR:Renvoyer en rédaction@en_US:Return to edition@', '@PRO_REDACTEUR@PRO_VALIDATEUR@PRO_ROOT@PRO_ROOT_SITE@', 1, NULL, NULL, 0),
(9, 'PST_AREDIGER', 'PST_ENLIGNE', '@fr_FR:Mettre en ligne@en_US:Publish@', '@PRO_VALIDATEUR@PRO_ROOT@PRO_ROOT_SITE@', 3, 'pre_PST_ENLIGNE', 'post_PST_ENLIGNE', 0),
(10, 'PST_ENLIGNE', 'PST_HORSLIGNE', '@fr_FR:Mettre hors ligne@en_US:Archive@', '@PRO_VALIDATEUR@PRO_ROOT@PRO_ROOT_SITE@', 2, 'pre_PST_HORSLIGNE', 'post_PST_HORSLIGNE', 1),
(11, 'PST_HORSLIGNE', 'PST_AREDIGER', '@fr_FR:Renvoyer en rédaction@en_US:Return to edition@', '@PRO_REDACTEUR@PRO_VALIDATEUR@PRO_ROOT@PRO_ROOT_SITE@', 1, NULL, NULL, 0),
(12, 'PST_AVALIDER', 'PST_ENLIGNE', '@fr_FR:Mettre en ligne@en_US:Publish@', '@PRO_VALIDATEUR@PRO_ROOT@PRO_ROOT_SITE@', 4, 'pre_PST_ENLIGNE', 'post_PST_ENLIGNE', 0),
(13, 'PST_AREDIGER', 'PST_HORSLIGNE', '@fr_FR:Mettre hors ligne@en_US:Archive@', '@PRO_ROOT@PRO_ROOT_SITE@PRO_VALIDATEUR@', 4, 'pre_PST_HORSLIGNE', 'post_PST_HORSLIGNE', 0),
(14, 'PST_AVALIDER', 'PST_HORSLIGNE', '@fr_FR:Mettre hors ligne@en_US:Archive@', '@PRO_ROOT@PRO_ROOT_SITE@', 5, 'pre_PST_HORSLIGNE', 'post_PST_HORSLIGNE', 0)");

$app->dbh->exec("INSERT INTO `OFF_PAGE`
(`SIT_CODE`, `ID_UTILISATEURVERROU`, `ID_WEBOTHEQUE_IMAGE`, `ID_WEBOTHEQUE_LIENEXTERNE`, `ID_PAGE_REDIRECT`, `ID_STYLEDYNAMIQUE`, `PST_CODE`,     `PGS_CODE`, `PSS_CODE`, `PAG_IDPERE`, `PAG_TITRE`, `PAG_TITRE_MENU`, `PAG_TITRE_REFERENCEMENT`, `PAG_TITLE`, `PAG_ACCROCHE`, `PAG_METADESCRIPTION`, `PAG_POIDS`, `PAG_VISIBLE_MENU`, `PAG_MOTCLE1`, `PAG_MOTCLE2`, `PAG_MOTCLE3`, `PAG_MOTCLE4`, `PAG_MOTCLE5`, `PAG_DATEONLINE`, `PAG_DATEONLINE_ON`, `PAG_DATEOFFLINE`, `PAG_DATEOFFLINE_ON`, `PAG_DATEVERROU`, `PAG_DATEMODIFICATION`, `PAG_URLREWRITING`, `PAG_GOOGLEFREQUENCE`, `PAG_GOOGLEPRIORITE`, `PAG_EXCLURECHERCHE`, `PAG_MASQUERGAUCHE`, `PAG_MASQUERDROITE`) VALUES
(" . $app->dbh->quote($SIT_CODE) . " , NULL,                   NULL,                  NULL,                        NULL,               NULL,                'PST_AREDIGER', NULL,       NULL,       NULL,         'Accueil',   'Accueil',        NULL,                      NULL,        NULL,           NULL,                  1,           1,                  NULL,          NULL,          NULL,          NULL,          NULL,          unix_timestamp(), NULL,                 2082668400,       NULL,                 NULL,             unix_timestamp(),       NULL,               NULL,                  NULL,                 0,                    0,                    0)");

$app->dbh->exec("INSERT INTO `DD_IMAGEFORMAT` (`IMF_CODE`, `GAB_CODE`, `IMF_LIBELLE`, `IMF_LARGEUR`, `IMF_HAUTEUR`, `IMF_QUALITE`, `IMF_AFFECTABLE`, `IMF_DE`, `IMF_ACTION`) VALUES
('IMF_LARGE', 'GAB_DEFAULT', 'Grand (600*400)', 600, 400, 60, 1, '', 'resize'),
('IMF_MEDIUM', 'GAB_DEFAULT', 'Moyen (300*200)', 300, 200, 60, 1, '', 'resize'),
('IMF_SMALL', 'GAB_DEFAULT', 'Petit (90*60)', 90, 60, 60, 1, '', 'resize')");

$app->dbh->exec("INSERT INTO `DD_COMMENTAIRE_LIAISONTYPE` (`MOD_CODE`, `PRO_CODE`, `CLI_CLASSNOM`, `CLI_CLASSFILE`, `CLI_CHEMINFICHE`) VALUES
('MOD_CORE', 'PRO_COMMENTAIRE', 'Page', 'class.db_page.php', '/cms/cms_pseudo.php?idtf=')");

$app->dbh->exec("INSERT INTO HISTORIQUE_UTILISATEUR (ID_HISTORIQUE_UTILISATEUR, SIT_CODE, ID_UTILISATEUR, HIS_DATE, HIS_DETAIL, HIS_UTILISATEUR, HIS_NBACTION) values
(1, " . $app->dbh->quote($SIT_CODE) . ", 1, unix_timestamp(), '', '', 0)");

$app->dbh->exec("INSERT INTO HISTORIQUE_PAGE (ID_HISTORIQUE_PAGE, SIT_CODE, ID_PAGE, ID_HISTORIQUE_UTILISATEUR, ID_PARAGRAPHE, ID_REVISION, HIS_ACTION, HIS_TYPE, HIS_DETAIL, HIS_DATE, HIS_INFO) values
(1, " . $app->dbh->quote($SIT_CODE) . ", 1, 1, NULL, NULL, 'CREATION', 'PAGE', '', unix_timestamp(), '')");

$app->dbh->exec("INSERT INTO `STAT_GA_MEDIUM` (`GAM_CODE`, `GAM_LIBELLE`, `GAM_ORDRE`) VALUES
('(none)', 'acces_direct', 1),
('(not set)', 'autres', 2),
('email', 'emailing', 3),
('organic', 'moteur_recherche', 4),
('referral', 'sites_affluents', 5),
('cpc', 'lien_sponsorises', 6)");

$sql = 'SELECT WBT_CODE FROM DD_WEBOTHEQUETYPE';
foreach ($app->dbh->query($sql)->fetchAll(PDO::FETCH_COLUMN) as $WBT_CODE) {
    $app->dbh->exec("INSERT INTO WEBOTHEQUECATEGORIE (SIT_CODE, WBT_CODE, CAT_LIBELLE) VALUES
        (" . $app->dbh->quote($SIT_CODE) . ", " . $app->dbh->quote($WBT_CODE) . ", 'Racine')");
}
$app->dbh->exec("insert into FORMULAIRECATEGORIE (SIT_CODE, CAT_LIBELLE) VALUES
    (" . $app->dbh->quote($SIT_CODE) . ", 'Racine')");
