<?php
/**
 *
 * Génération automatique du schéma de l'application
 * Date : 2010/09/22 17:42:02
 *
 * Modules :
 * > core (5.6)
 *
 * Known Issues :
 * - Les caractères ', ", \ ne sont pas pris de manière totalement satisfaisante au sein des valeurs $type pour les champs
 * - Sous mysql l'attribut "on update CURRENT_TIMESTAMP" n'est pas pris en charge (+ limitations similaires sur les manipulations des dates par défaut)
 *
 *
 * *****************************************************************************
 * Design des champs:
 * {dbStructTable}->$name (
 *      $type,         // Type de champ
 *      $len=0,        // Longueur du champ (0 = longueur par défaut du type)
 *      $attr=null,    // Attribut suplémentaire ['unsigned, etc.']
 *      $null=true,    // null or not null ?
 *      $default=false,// valeur par défaut (null => Default null, false => aucune)
 *      $extra=''      // extra de type autoincrement, etc, etc
 * );
 * > EX :
 * > $s->DE_EX->->ID_EXEMPLE           ('int',11,'unsigned',false,false,'auto_increment')
 *
 * La clé primaire:
 * {dbStructTable}->primary(
 *      $name,  // Nom de la clé primaire
 *      $col    // Nom de la ou des colonnes utilisées pour former la clé primaire
 * );
 * > EX :
 * > $s->DE_EX->primary('PRIMARY', 'ID_TEST', 'ID_WEBOTHEQUE');
 *
 * Les clés uniques:
 * {dbStructTable}->unique(
 *      $name,  // Nom de la clé primaire
 *      $col    // Nom de la ou des colonnes utilisées pour former la clé unique
 * );
 * > EX :
 * > $s->DE_EX->unique('DE_EX_uk_ID_WEBOTHEQUE_EX_NUM', 'ID_WEBOTHEQUE', 'EX_NUM');
 *
 * Les index:
 * {dbStructTable}->index(
 *      $name,  // Nom de l'index
 *      $type,  // Type d'index (btree pour InnoDB)
 *      $col    // une ou plusieurs colonnes cible de l'index (un nom de colonne par parametre de la fonction)
 * );
 * > EX :
 * > $s->DE_EX->index('DE_EX_idx_EX_DATES','btree','EX_DATE_DEBUT', 'EX_DATE_FIN');
 *
 * Les clés étrangères:
 * {dbStructTable}->reference(
 *      $name,          // Nom de la clé étrangère
 *      $c_cols,        // Nom de la colonne cible
 *      $p_table,       // Nom de la table principale
 *      $p_cols,        // Nom de la colonne principale
 *      $update=false,  // Comportement sur l'update ?
 *      $delete=false   // Comportement sur le delete ?
 * );
 * > EX :
 * > $s->DE_EX->reference('DE_EX_fk_DD_SITE','SIT_CODE','DD_SITE','SIT_CODE', 'cascade', 'delete');
 * *****************************************************************************

 */
if (! ($_s instanceof dbStruct)) {
    throw new Exception('No valid schema object');
}

/*
 * Tables
 * --------------------------------------------------------
 */

$_s->ABREVIATION->ID_ABREVIATION('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->ABR_ABREVIATION('varchar', 255)
    ->ABR_LIBELLE('varchar', 255)
    ->ABR_LANGUE('varchar', 255)
    ->ABR_TAGNAME('varchar', 255)
    ->primary('PRIMARY', 'ID_ABREVIATION')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->reference('ABREVIATION_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');

$_s->ALERTE->SIT_CODE('varchar', 30)
    ->ALT_MESSAGE('text', 0, '', false)
    ->ALT_DATE('int', 11, 'unsigned')
    ->unique('SIT_CODE', 'SIT_CODE')
    ->reference('ALERTE_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');

$_s->DD_EMAILTEMPLATE->EMT_CODE('varchar', 30, '', false)
    ->MOD_CODE('varchar', 30, '', false)
    ->EMT_DESCRIPTION('varchar', 255, '', false)
    ->EMT_EXPEDITEUR('varchar', 5, '', false, 'CMS')
    ->EMT_EXPEDITEURFROM('varchar', 255, '', false)
    ->EMT_EXPEDITEURFROMNAME('varchar', 255, '', false)
    ->EMT_SUJET('varchar', 255, '', false)
    ->EMT_BODYHTML('text', '', '', false)
    ->primary('PRIMARY', 'EMT_CODE')
    ->index('MOD_CODE', 'btree', 'MOD_CODE')
    ->reference('DD_EMAILTEMPLATE_MOD_CODE', 'MOD_CODE', 'DD_MODULE', 'MOD_CODE');

$_s->DD_EMAILTEMPLATEKEY->EMT_CODE('varchar', 30, '', false)
    ->EMK_LIBELLE('varchar', 255, '', false)
    ->EMK_DESCRIPTION('varchar', 255, '', false)
    ->primary('PRIMARY', 'EMT_CODE', 'EMK_LIBELLE')
    ->reference('DD_EMAILTEMPLATEKEY_EMT_CODE', 'EMT_CODE', 'DD_EMAILTEMPLATE', 'EMT_CODE');

$_s->DD_FORMULAIREQUESTIONTYPE->QTY_CODE('varchar', 30, '', false)
    ->QTY_LIBELLE('varchar', 255)
    ->QTY_GROUPE('varchar', 255)
    ->primary('PRIMARY', 'QTY_CODE');

$_s->DD_GABARIT->GAB_CODE('varchar', 30, '', false)
    ->GAB_LIBELLE('varchar', 255, '', false)
    ->GAB_PATH('varchar', 255, '', false)
    ->GAB_CSS_PATH('varchar', 255, '', false)
    ->GAB_PRINT_CSS_PATH('varchar', 255, '', false)
    ->primary('PRIMARY', 'GAB_CODE');

$_s->DD_GABARITIMAGE->GBI_CODE('varchar', 30, '', false)
    ->GAB_CODE('varchar', 30, '', false)
    ->GBI_LIBELLE('varchar', 255, '', false)
    ->GBI_PATH('varchar', 255, '', false)
    ->primary('PRIMARY', 'GBI_CODE')
    ->index('GAB_CODE', 'btree', 'GAB_CODE')
    ->reference('DD_GGABARITIMAGE_ibfk_1', 'GAB_CODE', 'DD_GABARIT', 'GAB_CODE');

$_s->DD_GABARITSTYLE->GBS_CODE('varchar', 30, '', false)
    ->GAB_CODE('varchar', 30, '', false)
    ->GBS_LIBELLE('varchar', 255, '', false)
    ->GBS_PATH('varchar', 255, '', false)
    ->GBS_EDITOR_PATH('varchar', 255, '', false)
    ->primary('PRIMARY', 'GBS_CODE')
    ->index('GAB_CODE', 'btree', 'GAB_CODE')
    ->reference('DD_GABARITSTYLE_ibfk_1', 'GAB_CODE', 'DD_GABARIT', 'GAB_CODE');

$_s->DD_IMAGEFORMAT->IMF_CODE('varchar', 30, '', false)
    ->GAB_CODE('varchar', 30, '', false)
    ->IMF_LIBELLE('varchar', 255, '', false)
    ->IMF_LARGEUR('int', 6, 'unsigned', false, 0)
    ->IMF_HAUTEUR('int', 6, 'unsigned', false, 0)
    ->IMF_QUALITE('int', 6, 'unsigned', false, 90)
    ->IMF_AFFECTABLE('tinyint', 1, 'unsigned', false, 1)
    ->IMF_DE('varchar', 1000, '', false)
    ->IMF_ACTION('enum(\'resize\',\'crop\')', 0, '', false, 'resize')
    ->primary('PRIMARY', 'IMF_CODE', 'GAB_CODE')
    ->index('GAB_CODE', 'btree', 'GAB_CODE')
    ->reference('DD_IMAGEFORMAT_ibfk_1', 'GAB_CODE', 'DD_GABARIT', 'GAB_CODE');

$_s->DD_LANGUE->LNG_CODE('char', 5, '', false)
    ->LNG_LIBELLE('varchar', 255)
    ->LNG_FO('tinyint', 1, 'unsigned', false, 0)
    ->LNG_BO('tinyint', 1, 'unsigned', false, 0)
    ->primary('PRIMARY', 'LNG_CODE');

$_s->DD_LIAISON->LIA_CODE('varchar', 30, '', false)
    ->LIA_LIBELLE('varchar', 255, '', false)
    ->LIA_NOM_CHAMP_ID('varchar', 255, '', false)
    ->LIA_LIBELLE_CHAMP('varchar', 255, '', false)
    ->LIA_NOM_CHAMP('varchar', 255, '', false)
    ->LIA_NOM_FICHIER('varchar', 255, '', false)
    ->primary('PRIMARY', 'LIA_CODE');

$_s->DD_MODULE->MOD_CODE('varchar', 30, '', false)
    ->MOD_LIBELLE('varchar', 255, '', false)
    ->MOD_GROUPE('varchar', 255, '', false)
    ->MOD_OBLIGATOIRE('tinyint', 1, 'unsigned', false, 0)
    ->MOD_POIDS('int', 11, 'unsigned', false, 100)
    ->primary('PRIMARY', 'MOD_CODE');

$_s->DD_PAGESPECIALE->PGS_CODE('varchar', 30, '', false)
    ->MOD_CODE('varchar', 30, '', false)
    ->PGS_LIBELLE('varchar', 255)
    ->primary('PRIMARY', 'PGS_CODE')
    ->index('MOD_CODE', 'btree', 'MOD_CODE')
    ->reference('DD_PAGESPECIALE_ibfk_1', 'MOD_CODE', 'DD_MODULE', 'MOD_CODE');

$_s->DD_PAGESTATUT->PST_CODE('varchar', 30, '', false)
    ->PST_LIBELLE('varchar', 255)
    ->PST_POIDS('int', 6, 'unsigned')
    ->primary('PRIMARY', 'PST_CODE');

$_s->DD_PAGESTYLE->PSS_CODE('varchar', 30, '', false)
    ->GBS_CODE('varchar', 30, '', false)
    ->PSS_LIBELLE('varchar', 255, '', false)
    ->PSS_PATH('varchar', 255, '', false)
    ->primary('PRIMARY', 'PSS_CODE', 'GBS_CODE')
    ->index('DD_PAGESTYLE_GBS_CODE', 'btree', 'GBS_CODE')
    ->reference('DD_PAGESTYLE_GBS_CODE', 'GBS_CODE', 'DD_GABARITSTYLE', 'GBS_CODE');

$_s->DD_PARAGRAPHESTYLE->PRS_CODE('varchar', 30, '', false)
    ->GAB_CODE('varchar', 30, '', false)
    ->PRT_CODE_ARRAY('varchar', 255, '', false)
    ->PRS_COLONNE('varchar', 255, '', false)
    ->PRS_LIBELLE('varchar', 255)
    ->PRS_WIDTH('varchar', 255)
    ->primary('PRIMARY', 'PRS_CODE', 'GAB_CODE')
    ->index('GAB_CODE', 'btree', 'GAB_CODE')
    ->reference('DD_PARAGRAPHESTYLE_ibfk_1', 'GAB_CODE', 'DD_GABARIT', 'GAB_CODE');

$_s->DD_PARAGRAPHETYPE->PRT_CODE('varchar', 30, '', false)
    ->PRT_LIBELLE('varchar', 255)
    ->PRT_COLONNE('varchar', 255, '', false)
    ->PRT_POIDS('int', 6, 'unsigned')
    ->primary('PRIMARY', 'PRT_CODE');

$_s->DD_PROFIL->PRO_CODE('varchar', 30, '', false)
    ->PRO_LIBELLE('varchar', 255)
    ->PRO_PAGE('tinyint', 1, 'unsigned', false, 0)
    ->primary('PRIMARY', 'PRO_CODE');

$_s->DD_RECHERCHE->ID_RECHERCHE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->REC_LIBELLE('varchar', 255, '', false)
    ->MOD_CODE('varchar', 30, '', false)
    ->PGS_CODE('varchar', 30)
    ->TPL_CODE('varchar', 30, '', false)
    ->REC_TABLE('varchar', 255, '', false)
    ->REC_IDENTIFIANT('varchar', 255, '', false)
    ->REC_RESULTATTITRE('varchar', 255, '', false)
    ->REC_RESULTATDESCRIPTION('varchar', 255, '', false)
    ->REC_CHAMP1('varchar', 255, '', false)
    ->REC_POIDS1('int', 11, 'unsigned', false)
    ->REC_CHAMP2('varchar', 255, '', false)
    ->REC_POIDS2('int', 11, 'unsigned', false)
    ->REC_FILTRE('varchar', 255, '', false)
    ->REC_FILTRESITE('tinyint', 1, 'unsigned', false, 0)
    ->REC_SITEMAP('tinyint', 1, 'unsigned', false, 0)
    ->REC_GOOGLEPRIORITE('varchar', 255, '', false)
    ->REC_GOOGLEFREQUENCE('varchar', 255, '', false)
    ->REC_GOOGLELASTMOD('varchar', 255, '', false)
    ->primary('PRIMARY', 'ID_RECHERCHE')
    ->index('PGS_CODE', 'btree', 'PGS_CODE')
    ->index('TPL_CODE', 'btree', 'TPL_CODE')
    ->index('MOD_CODE', 'btree', 'MOD_CODE')
    ->reference('DD_RECHERCHE_PGS_CODE', 'PGS_CODE', 'DD_PAGESPECIALE', 'PGS_CODE')
    ->reference('DD_RECHERCHE_TPL_CODE', 'TPL_CODE', 'DD_TEMPLATE', 'TPL_CODE')
    ->reference('DD_RECHERCHE_MOD_CODE', 'MOD_CODE', 'DD_MODULE', 'MOD_CODE');

$_s->DD_SITE->SIT_CODE('varchar', 30, '', false)
    ->GAB_CODE('varchar', 30, '', false)
    ->GBS_CODE('varchar', 30, '', false)
    ->GBI_CODE('varchar', 30, '', false)
    ->LNG_CODE('char', 5, '', false)
    ->SIT_LIBELLE('varchar', 255, '', false)
    ->SIT_TITLE('varchar', 255, '', false)
    ->SIT_RECHERCHE('varchar', 255, '', false)
    ->SIT_HOST('varchar', 255, '', false)
    ->SIT_EMAIL('varchar', 255, '', false)
    ->SIT_SUPPORTKEY('varchar', 255, '', false)
    ->SIT_RSS_ACTU('varchar', 255, '', false)
    ->SIT_LOGO('varchar', 255, '', false)
    ->SIT_FAVICON('varchar', 255, '', false)
    ->SIT_TXTMOBILEHIDDEN('text', '', '', false)
    ->SIT_GA_TAG('text', '', '', false)
    ->SIT_GA_TAG_CNIL('tinyint', 1, 'unsigned', false, 0)
    ->SIT_GA_ID('varchar', 255, '', false)
    ->SIT_GA_KEYFILE('varchar', 255, '', false)
    ->SIT_GA_ID_SITE('int', 11, 'unsigned')
    ->SIT_RSS_WEBMARKET('varchar', 255, '', false)
    ->SIT_EXT_DOC('varchar', 1000, '', false, ".txt\n.rtf\n.pdf\n.doc\n.xls\n.zip\n.ppt\n.gif\n.jpg\n.jpeg\n.bmp\n.png\n.docx\n.pptx\n.odt\n.docm\n.dotx\n.dotm\n.xlsx\n.xlsm\n.xltx\n.xltm\n.xlsb\n.pptm\n.potx\n.potm\n.ppsx\n.ppsm\n.sldx\n.sldm\n")
    ->SIT_EXT_IMAGE('varchar', 1000, '', false, ".gif\n.jpg\n.jpeg\n.bmp\n.png\n")
    ->SIT_EXT_FLASH('varchar', 1000, '', false, ".swf\n")
    ->SIT_EXT_VIDEO('varchar', 1000, '', false, ".flv\n.mp4\n.webm\n.ogv\n")
    ->SIT_EXT_MUSIC('varchar', 1000, '', false, ".mp3\n.ogg\n")
    ->SIT_CHECKMD5('tinyint', 1, 'unsigned', false, 1)
    ->SIT_PAGE_TXTACCROCHE('tinyint', 1, 'unsigned', false, 1)
    ->SIT_PAGE_IMGACCROCHE('tinyint', 1, 'unsigned', false, 1)
    ->SIT_PAGE_HTTPS('tinyint', 1, 'unsigned', false, 0)
    ->SIT_PAGE_CACHE('tinyint', 1, 'unsigned', false, 0)
    ->SIT_CONNECTION_MAX('int', 6, 'unsigned', false, 5)
    ->SIT_CONNECTION_TTL('int', 6, 'unsigned', false, 10)
    ->SIT_MAXONLINEUSER('smallint', 6, 'unsigned', false)
    ->SIT_DATEMAXONLINEUSER('int', 11, 'unsigned', false)
    ->SIT_AUTHOR('varchar', 255, '', false)
    ->primary('PRIMARY', 'SIT_CODE')
    ->index('LNG_CODE', 'btree', 'LNG_CODE')
    ->index('GAB_CODE', 'btree', 'GAB_CODE')
    ->index('GBS_CODE', 'btree', 'GBS_CODE')
    ->index('GBI_CODE', 'btree', 'GBI_CODE')
    ->reference('DD_SITE_ibfk_1', 'GAB_CODE', 'DD_GABARIT', 'GAB_CODE')
    ->reference('DD_SITE_ibfk_2', 'GBS_CODE', 'DD_GABARITSTYLE', 'GBS_CODE')
    ->reference('DD_SITE_ibfk_3', 'GBI_CODE', 'DD_GABARITIMAGE', 'GBI_CODE')
    ->reference('DD_SITE_ibfk_4', 'LNG_CODE', 'DD_LANGUE', 'LNG_CODE');

$_s->DD_TEMPLATE->TPL_CODE('varchar', 30, '', false)
    ->MOD_CODE('varchar', 30, '', false)
    ->TPL_LIBELLE('varchar', 255)
    ->TPL_PAGE('varchar', 255)
    ->TPL_AFFECTABLE('tinyint', 1, 'unsigned', false, 1)
    ->TPL_LINKABLE('tinyint', 1, 'unsigned', false, 0)
    ->TPL_COLONNE('varchar', 255, '', false)
    ->TPL_POPUP_RESTRICTION('varchar', 255, '', false)
    ->TPL_PARAMETRAGE('text')
    ->TPL_PARAMETRAGE_CLES('text')
    ->TPL_URLCODE('varchar', 255)
    ->PGS_CODE('varchar', 30)
    ->TPL_REWRITEURL('varchar', 255)
    ->TPL_REWRITEMETHOD('varchar', 255)
    ->primary('PRIMARY', 'TPL_CODE')
    ->unique('TPL_URLCODE', 'TPL_URLCODE')
    ->index('MOD_CODE', 'btree', 'MOD_CODE')
    ->index('PGS_CODE', 'btree', 'PGS_CODE')
    ->reference('DD_TEMPLATE_ibfk_1', 'MOD_CODE', 'DD_MODULE', 'MOD_CODE')
    ->reference('DD_TEMPLATE_ibfk_2', 'PGS_CODE', 'DD_PAGESPECIALE', 'PGS_CODE');

$_s->DD_TRADUCTION->TRA_CODE('varchar', 255, '', false)
    ->MOD_CODE('varchar', 30, '', false)
    ->TRA_DESCRIPTION('varchar', 255, '', false)
    ->TRA_MULTILIGNE('tinyint', 1, 'unsigned', false, 0)
    ->primary('PRIMARY', 'TRA_CODE')
    ->index('MOD_CODE', 'btree', 'MOD_CODE')
    ->reference('DD_TRADUCTION_ibfk_1', 'MOD_CODE', 'DD_MODULE', 'MOD_CODE');

$_s->DD_WEBOTHEQUETYPE->WBT_CODE('varchar', 30, '', false)
    ->WBT_LIBELLE('varchar', 255)
    ->primary('PRIMARY', 'WBT_CODE');

$_s->FORMULAIRE->ID_FORMULAIRE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->ID_FORMULAIRECATEGORIE('int', 11, 'unsigned')
    ->FRM_LIBELLE('varchar', 255)
    ->FRM_LIBELLE_BOUTON('varchar', 255)
    ->FRM_TRACABLE('tinyint', 1, 'unsigned', false, 0)
    ->FRM_TRACEIP('tinyint', 1, '', true, 0)
    ->FRM_NOTIFICATION('tinyint', 1, 'unsigned', false, 0)
    ->FRM_NOTIFICATION_EMAIL('varchar', 255)
    ->FRM_ETATREPONSE('text')
    ->FRM_ACCUSERECEPTION('text')
    ->FRM_MENTION_CNIL('tinyint', 1, '', false, 1)
    ->FRM_MESSAGEREPONSE('text')
    ->FRM_EXPEDITEUR_NOM('varchar', 255, '', false, WEBMASTER_NOM)
    ->FRM_EXPEDITEUR_EMAIL('varchar', 255, '', false, WEBMASTER_EMAIL)
    ->primary('PRIMARY', 'ID_FORMULAIRE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_FORMULAIRECATEGORIE', 'btree', 'ID_FORMULAIRECATEGORIE')
    ->reference('FORMULAIRE_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('FORMULAIRE_ibfk_2', 'ID_FORMULAIRECATEGORIE', 'FORMULAIRECATEGORIE', 'ID_FORMULAIRECATEGORIE');

$_s->FORMULAIRECATEGORIE->ID_FORMULAIRECATEGORIE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->CAT_IDPARENT('int', 11, 'unsigned')
    ->SIT_CODE('varchar', 30, '', false)
    ->CAT_LIBELLE('varchar', 255)
    ->primary('PRIMARY', 'ID_FORMULAIRECATEGORIE')
    ->index('CAT_IDPERE', 'btree', 'CAT_IDPARENT')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->reference('FORMULAIRECATEGORIE_ibfk_1', 'CAT_IDPARENT', 'FORMULAIRECATEGORIE', 'ID_FORMULAIRECATEGORIE')
    ->reference('FORMULAIRECATEGORIE_ibfk_2', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');

$_s->FORMULAIREGROUPE->ID_FORMULAIREGROUPE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_FORMULAIRE('int', 11, 'unsigned', false)
    ->FMG_LIBELLE('varchar', 255)
    ->FMG_POIDS('int', 6, 'unsigned')
    ->FMG_VISIBLE('tinyint', 1, 'unsigned', false, 1)
    ->FMG_LIBELLEVISIBLE('tinyint', 1, 'unsigned', false, 1)
    ->primary('PRIMARY', 'ID_FORMULAIREGROUPE')
    ->index('ID_FORMULAIRE', 'btree', 'ID_FORMULAIRE')
    ->index('FMG_POIDS', 'btree', 'FMG_POIDS')
    ->reference('FORMULAIREGROUPE_ibfk_1', 'ID_FORMULAIRE', 'FORMULAIRE', 'ID_FORMULAIRE');

$_s->FORMULAIREQUESTION->ID_FORMULAIREQUESTION('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_FORMULAIREGROUPE('int', 11, 'unsigned', false)
    ->QTY_CODE('varchar', 30, '', false)
    ->QST_LIBELLE('varchar', 255)
    ->QST_POIDS('int', 6, 'unsigned')
    ->QST_VISIBLE('tinyint', 1, 'unsigned', false, 1)
    ->QST_OBLIGATOIRE('tinyint', 1, 'unsigned', false, 0)
    ->QST_HEIGHT('int', 6, 'unsigned')
    ->QST_WIDTH('int', 6, 'unsigned')
    ->QST_MAXLENGTH('int', 6, 'unsigned')
    ->QST_VALEUR('text')
    ->QST_MULTIPLE('tinyint', 1, 'unsigned', false, 0)
    ->QST_ENTETE('tinyint', 1, 'unsigned', false, 0)
    ->QST_LIBELLEVISIBLE('tinyint', 1, 'unsigned', false, 1)
    ->QST_COMMENTAIRE('text')
    ->QST_MESSAGEAIDE('varchar', 255, null, true, null)
    ->QST_PLACEHOLDER('varchar', 255, null, true, null)
    ->primary('PRIMARY', 'ID_FORMULAIREQUESTION')
    ->index('QTY_CODE', 'btree', 'QTY_CODE')
    ->index('ID_FORMULAIREGROUPE', 'btree', 'ID_FORMULAIREGROUPE')
    ->reference('FORMULAIREQUESTION_ibfk_1', 'ID_FORMULAIREGROUPE', 'FORMULAIREGROUPE', 'ID_FORMULAIREGROUPE')
    ->reference('FORMULAIREQUESTION_ibfk_2', 'QTY_CODE', 'DD_FORMULAIREQUESTIONTYPE', 'QTY_CODE');

$_s->FORMULAIREREPONSE->ID_FORMULAIREREPONSE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_FORMULAIRE('int', 11, 'unsigned', false)
    ->ID_UTILISATEUR('int', 11, 'unsigned')
    ->REP_IPUTILISATEUR('varchar', 255)
    ->REP_DATE('int', 11, 'unsigned')
    ->REP_ETAT('varchar', 255)
    ->REP_COMMENTAIRE('text')
    ->primary('PRIMARY', 'ID_FORMULAIREREPONSE')
    ->index('ID_FORMULAIRE', 'btree', 'ID_FORMULAIRE')
    ->index('ID_UTILISATEUR', 'btree', 'ID_UTILISATEUR')
    ->reference('FORMULAIREREPONSE_ibfk_1', 'ID_FORMULAIRE', 'FORMULAIRE', 'ID_FORMULAIRE')
    ->reference('FORMULAIREREPONSE_ibfk_2', 'ID_UTILISATEUR', 'UTILISATEUR', 'ID_UTILISATEUR');

$_s->FORMULAIREREPONSEDETAIL->ID_FORMULAIREREPONSEDETAIL('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_FORMULAIREREPONSE('int', 11, 'unsigned', false)
    ->ID_FORMULAIREQUESTION('int', 11, 'unsigned', false)
    ->RED_VALEUR('text')
    ->primary('PRIMARY', 'ID_FORMULAIREREPONSEDETAIL')
    ->index('ID_FORMULAIREREPONSE', 'btree', 'ID_FORMULAIREREPONSE')
    ->index('ID_FORMULAIREQUESTION', 'btree', 'ID_FORMULAIREQUESTION')
    ->reference('FORMULAIREREPONSEDETAIL_ibfk_1', 'ID_FORMULAIREREPONSE', 'FORMULAIREREPONSE', 'ID_FORMULAIREREPONSE')
    ->reference('FORMULAIREREPONSEDETAIL_ibfk_2', 'ID_FORMULAIREQUESTION', 'FORMULAIREQUESTION', 'ID_FORMULAIREQUESTION');

$_s->FORMULAIRE_UTILISATEUR->ID_FORMULAIRE('int', 11, 'unsigned', false)
    ->ID_UTILISATEUR('int', 11, 'unsigned', false)
    ->primary('PRIMARY', 'ID_FORMULAIRE', 'ID_UTILISATEUR')
    ->index('ID_UTILISATEUR', 'btree', 'ID_UTILISATEUR')
    ->reference('FORMULAIRE_UTILISATEUR_ibfk_1', 'ID_FORMULAIRE', 'FORMULAIRE', 'ID_FORMULAIRE')
    ->reference('FORMULAIRE_UTILISATEUR_ibfk_2', 'ID_UTILISATEUR', 'UTILISATEUR', 'ID_UTILISATEUR');

$_s->GROUPE->ID_GROUPE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->GRP_LIBELLE('varchar', 255)
    ->GRP_DEFAUT_UTILISATEUR('tinyint', 1, 'unsigned', false, 0)
    ->primary('PRIMARY', 'ID_GROUPE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->reference('GROUPE_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');

$_s->GROUPE_OFF_PAGE->ID_GROUPE('int', 11, 'unsigned', false)
    ->ID_PAGE('int', 11, 'unsigned', false)
    ->primary('PRIMARY', 'ID_GROUPE', 'ID_PAGE')
    ->index('ID_PAGE', 'btree', 'ID_PAGE')
    ->reference('GROUPE_OFF_PAGE_ibfk_2', 'ID_PAGE', 'OFF_PAGE', 'ID_PAGE')
    ->reference('GROUPE_OFF_PAGE_ibfk_1', 'ID_GROUPE', 'GROUPE', 'ID_GROUPE');

$_s->GROUPE_ON_PAGE->ID_GROUPE('int', 11, 'unsigned', false)
    ->ID_PAGE('int', 11, 'unsigned', false)
    ->primary('PRIMARY', 'ID_GROUPE', 'ID_PAGE')
    ->index('ID_PAGE', 'btree', 'ID_PAGE')
    ->reference('GROUPE_ON_PAGE_ibfk_2', 'ID_PAGE', 'ON_PAGE', 'ID_PAGE')
    ->reference('GROUPE_ON_PAGE_ibfk_1', 'ID_GROUPE', 'GROUPE', 'ID_GROUPE');

$_s->GROUPE_SITE->ID_GROUPE('int', 11, 'unsigned', false)
    ->SIT_CODE('varchar', 30, '', false)
    ->primary('PRIMARY', 'ID_GROUPE', 'SIT_CODE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->reference('GROUPE_SITE_ibfk_2', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('GROUPE_SITE_ibfk_1', 'ID_GROUPE', 'GROUPE', 'ID_GROUPE');

$_s->GROUPE_UTILISATEUR->ID_GROUPE('int', 11, 'unsigned', false)
    ->ID_UTILISATEUR('int', 11, 'unsigned', false)
    ->primary('PRIMARY', 'ID_GROUPE', 'ID_UTILISATEUR')
    ->index('ID_UTILISATEUR', 'btree', 'ID_UTILISATEUR')
    ->reference('GROUPE_UTILISATEUR_ibfk_1', 'ID_GROUPE', 'GROUPE', 'ID_GROUPE')
    ->reference('GROUPE_UTILISATEUR_ibfk_5', 'ID_UTILISATEUR', 'UTILISATEUR', 'ID_UTILISATEUR');

$_s->HISTORIQUE_UTILISATEUR->ID_HISTORIQUE_UTILISATEUR('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->ID_UTILISATEUR('int', 11, 'unsigned')
    ->HIS_DATE('int', 11, 'unsigned', false)
    ->HIS_DETAIL('varchar', 255)
    ->HIS_UTILISATEUR('varchar', 255, '', false)
    ->HIS_NBACTION('int', 11, 'unsigned', false, 0)
    ->primary('PRIMARY', 'ID_HISTORIQUE_UTILISATEUR')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_UTILISATEUR', 'btree', 'ID_UTILISATEUR')
    ->index('HIS_NBACTION', 'btree', 'HIS_NBACTION')
    ->index('HIS_DATE', 'btree', 'HIS_DATE')
    ->reference('HISTORIQUE_UTILISATEUR_SIT_CODE', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');

$_s->HISTORIQUE_PAGE->ID_HISTORIQUE_PAGE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->ID_PAGE('int', 11, 'unsigned')
    ->ID_HISTORIQUE_UTILISATEUR('int', 11, 'unsigned')
    ->ID_PARAGRAPHE('int', 11, 'unsigned')
    ->ID_REVISION('int', 11)
    ->HIS_ACTION('varchar', 30, '', false)
    ->HIS_TYPE('varchar', 30, '', false)
    ->HIS_DETAIL('varchar', 255)
    ->HIS_DATE('int', 11, 'unsigned', false)
    ->HIS_INFO('varchar', 255, '', false)
    ->primary('PRIMARY', 'ID_HISTORIQUE_PAGE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_PAGE', 'btree', 'ID_PAGE')
    ->index('ID_HISTORIQUE_UTILISATEUR', 'btree', 'ID_HISTORIQUE_UTILISATEUR')
    ->index('ID_PARAGRAPHE', 'btree', 'ID_PARAGRAPHE')
    ->index('ID_REVISION', 'btree', 'ID_REVISION')
    ->index('HIS_ACTION', 'btree', 'HIS_ACTION')
    ->index('HIS_TYPE', 'btree', 'HIS_TYPE')
    ->index('HIS_DATE', 'btree', 'HIS_DATE')
    ->reference('HISTORIQUE_PAGE_SIT_CODE', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('HISTORIQUE_PAGE_ID_HISTORIQUE_UTILISATEUR', 'ID_HISTORIQUE_UTILISATEUR', 'HISTORIQUE_UTILISATEUR', 'ID_HISTORIQUE_UTILISATEUR');

$_s->HISTORIQUE_WEBOTHEQUE->ID_HISTORIQUE_WEBOTHEQUE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->ID_WEBOTHEQUE('int', 11, 'unsigned')
    ->ID_HISTORIQUE_UTILISATEUR('int', 11, 'unsigned')
    ->WBT_CODE('varchar', 30, '', false)
    ->HIS_ACTION('varchar', 30, '', false)
    ->HIS_DETAIL('varchar', 255)
    ->HIS_DATE('int', 11, 'unsigned', false)
    ->HIS_INFO('varchar', 255)
    ->primary('PRIMARY', 'ID_HISTORIQUE_WEBOTHEQUE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_WEBOTHEQUE', 'btree', 'ID_WEBOTHEQUE')
    ->index('ID_HISTORIQUE_UTILISATEUR', 'btree', 'ID_HISTORIQUE_UTILISATEUR')
    ->index('HIS_ACTION', 'btree', 'HIS_ACTION')
    ->index('HIS_DATE', 'btree', 'HIS_DATE')
    ->reference('HISTORIQUE_WEBOTHEQUE_SIT_CODE', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('HISTORIQUE_WEBOTHEQUE_ID_HISTORIQUE_UTILISATEUR', 'ID_HISTORIQUE_UTILISATEUR', 'HISTORIQUE_UTILISATEUR', 'ID_HISTORIQUE_UTILISATEUR');

$_s->HISTORIQUE_FORMULAIRE->ID_HISTORIQUE_FORMULAIRE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->ID_FORMULAIRE('int', 11, 'unsigned')
    ->ID_HISTORIQUE_UTILISATEUR('int', 11, 'unsigned')
    ->HIS_ACTION('varchar', 30, '', false)
    ->HIS_TYPE('varchar', 30, '', false)
    ->HIS_DETAIL('varchar', 255)
    ->HIS_DATE('int', 11, 'unsigned', false)
    ->HIS_INFO('varchar', 255)
    ->primary('PRIMARY', 'ID_HISTORIQUE_FORMULAIRE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_FORMULAIRE', 'btree', 'ID_FORMULAIRE')
    ->index('ID_HISTORIQUE_UTILISATEUR', 'btree', 'ID_HISTORIQUE_UTILISATEUR')
    ->index('HIS_ACTION', 'btree', 'HIS_ACTION')
    ->index('HIS_DATE', 'btree', 'HIS_DATE')
    ->reference('HISTORIQUE_FORMULAIRE_SIT_CODE', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('HISTORIQUE_FORMULAIRE_ID_HISTORIQUE_UTILISATEUR', 'ID_HISTORIQUE_UTILISATEUR', 'HISTORIQUE_UTILISATEUR', 'ID_HISTORIQUE_UTILISATEUR');

$_s->DD_HISTORIQUE_EXTERNE->HEX_CODE('varchar', 30, '', false)
    ->MOD_CODE('varchar', 30, '', false)
    ->HEX_TABLE('varchar', 30, '', false)
    ->HEX_CHAMP_ID('varchar', 30, '', false)
    ->HEX_CHAMP_LIBELLE('varchar', 30, '', false)
    ->index('HEX_CODE', 'btree', 'HEX_CODE')
    ->primary('PRIMARY', 'HEX_CODE');

$_s->HISTORIQUE_EXTERNE->ID_HISTORIQUE_EXTERNE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->HEX_CODE('varchar', 30, '', false)
    ->HIS_IDENTIFIANT('varchar', 30, '', false)
    ->ID_HISTORIQUE_UTILISATEUR('int', 11, 'unsigned')
    ->HIS_ACTION('varchar', 30, '', false)
    ->HIS_DETAIL('varchar', 255)
    ->HIS_DATE('int', 11, 'unsigned', false)
    ->HIS_INFO('varchar', 255)
    ->primary('PRIMARY', 'ID_HISTORIQUE_EXTERNE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_HISTORIQUE_UTILISATEUR', 'btree', 'ID_HISTORIQUE_UTILISATEUR')
    ->index('HEX_CODE', 'btree', 'HEX_CODE')
    ->index('HIS_ACTION', 'btree', 'HIS_ACTION')
    ->index('HIS_DATE', 'btree', 'HIS_DATE')
    ->reference('HISTORIQUE_EXTERNE_SIT_CODE', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('HISTORIQUE_EXTERNE_HEX_CODE', 'HEX_CODE', 'DD_HISTORIQUE_EXTERNE', 'HEX_CODE')
    ->reference('HISTORIQUE_EXTERNE_ID_HISTORIQUE_UTILISATEUR', 'ID_HISTORIQUE_UTILISATEUR', 'HISTORIQUE_UTILISATEUR', 'ID_HISTORIQUE_UTILISATEUR');

$_s->HISTORIQUE_ADMIN->ID_HISTORIQUE_ADMIN('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->ID_HISTORIQUE_UTILISATEUR('int', 11, 'unsigned')
    ->HIS_IDENTIFIANT('varchar', 255, '', false)
    ->HIS_ACTION('varchar', 30, '', false)
    ->HIS_TYPE('varchar', 30, '', false)
    ->HIS_DETAIL('varchar', 255, '', false)
    ->HIS_DATE('int', 11, 'unsigned', false)
    ->HIS_UTILISATEUR('varchar', 255, '', false)
    ->primary('PRIMARY', 'ID_HISTORIQUE_ADMIN')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_HISTORIQUE_UTILISATEUR', 'btree', 'ID_HISTORIQUE_UTILISATEUR')
    ->index('HIS_ACTION', 'btree', 'HIS_ACTION')
    ->index('HIS_TYPE', 'btree', 'HIS_TYPE')
    ->index('HIS_DATE', 'btree', 'HIS_DATE')
    ->reference('HISTORIQUE_ADMIN_SIT_CODE', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('HISTORIQUE_ADMIN_ID_HISTORIQUE_UTILISATEUR', 'ID_HISTORIQUE_UTILISATEUR', 'HISTORIQUE_UTILISATEUR', 'ID_HISTORIQUE_UTILISATEUR');

$_s->HISTORIQUE_CALENDRIER->HIC_DATE('varchar', 30, '', false)
    ->HIC_MONTH('varchar', 30, '', false)
    ->HIC_YEAR('int', 4, 'unsigned')
    ->primary('PRIMARY', 'HIC_DATE')
    ->index('HIC_MONTH', 'btree', 'HIC_MONTH')
    ->index('HIC_YEAR', 'btree', 'HIC_YEAR');

$_s->HISTORIQUE_PERIODE->ID_HISTORIQUE_PERIODE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->HIC_DATE('varchar', 30, '', false)
    ->HID_TYPEDONNEE('varchar', 30, '', false)
    ->
// PAGE / FORMULAIRE / WEBO / ADMIN / EXTERNE / UTILISATEUR
HID_IDENTIFIANT('varchar', 30, '', false)
    ->
// IDENTIFIANT (utilisateur, page ou formulaire) / HEX_CODE / WBT_CODE / SITE / UTILISATEUR
HID_INFO('varchar', 255, '', false)
    ->
// LIBELLE
HID_JOUR01('text')
    ->HID_JOUR02('text')
    ->HID_JOUR03('text')
    ->HID_JOUR04('text')
    ->HID_JOUR05('text')
    ->HID_JOUR06('text')
    ->HID_JOUR07('text')
    ->HID_JOUR08('text')
    ->HID_JOUR09('text')
    ->HID_JOUR10('text')
    ->HID_JOUR11('text')
    ->HID_JOUR12('text')
    ->HID_JOUR13('text')
    ->HID_JOUR14('text')
    ->HID_JOUR15('text')
    ->HID_JOUR16('text')
    ->HID_JOUR17('text')
    ->HID_JOUR18('text')
    ->HID_JOUR19('text')
    ->HID_JOUR20('text')
    ->HID_JOUR21('text')
    ->HID_JOUR22('text')
    ->HID_JOUR23('text')
    ->HID_JOUR24('text')
    ->HID_JOUR25('text')
    ->HID_JOUR26('text')
    ->HID_JOUR27('text')
    ->HID_JOUR28('text')
    ->HID_JOUR29('text')
    ->HID_JOUR30('text')
    ->HID_JOUR31('text')
    ->HID_TOTALACTION('int', 11, 'unsigned', false, 0)
    ->HID_LASTDATE('int', 11, 'unsigned', false, 0)
    ->HID_TOTALCONNEXION('int', 11, 'unsigned', false, 0)
    ->
// SpecifiX stat contributeur
HID_TOTALENLIGNE('int', 11, 'unsigned', false, 0)
    ->
// SpecifiX stat page
HID_TOTALAVALIDER('int', 11, 'unsigned', false, 0)
    ->
// SpecifiX stat page
HID_TOTALHORSLIGNE('int', 11, 'unsigned', false, 0)
    ->
// SpecifiX stat page

primary('PRIMARY', 'ID_HISTORIQUE_PERIODE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('HIC_DATE', 'btree', 'HIC_DATE')
    ->index('HID_TYPEDONNEE', 'btree', 'HID_TYPEDONNEE')
    ->index('HID_TOTALACTION', 'btree', 'HID_TOTALACTION')
    ->index('HID_LASTDATE', 'btree', 'HID_LASTDATE')
    ->index('HID_TOTALCONNEXION', 'btree', 'HID_TOTALCONNEXION')
    ->index('HID_TOTALENLIGNE', 'btree', 'HID_TOTALENLIGNE')
    ->index('HID_TOTALAVALIDER', 'btree', 'HID_TOTALAVALIDER')
    ->index('HID_TOTALHORSLIGNE', 'btree', 'HID_TOTALHORSLIGNE')
    ->reference('HISTORIQUE_PERIODE_SIT_CODE', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('HISTORIQUE_PERIODE_HIC_DATE', 'HIC_DATE', 'HISTORIQUE_CALENDRIER', 'HIC_DATE');

$_s->LANGUISME->ID_LANGUISME('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->LNG_LIBELLE('varchar', 255, '', false)
    ->LNG_LANGUE('varchar', 255, '', false)
    ->primary('PRIMARY', 'ID_LANGUISME')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->reference('LANGUISME_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');

$_s->LDAP->ID_LDAP('int', 11, 'unsigned', false, false, 'auto_increment')
    ->LDA_LIBELLE('varchar', 255)
    ->LDA_HOST('varchar', 255)
    ->LDA_PORT('varchar', 255)
    ->LDA_LDAPS('tinyint', 1, 'unsigned', false, 0)
    ->LDA_ACCOUNT('varchar', 255)
    ->LDA_PASSWORD('varchar', 255)
    ->LDA_BASEDN('varchar', 255)
    ->LDA_FILTER('varchar', 255)
    ->LDA_ATTRLOGIN('varchar', 255)
    ->primary('PRIMARY', 'ID_LDAP');

$_s->LIAISON_EXTERNE->ID_LIAISON_EXTERNE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->LIA_CODE_FROM('varchar', 30, '', false)
    ->ID_LIAISON_FROM('varchar', 32, '', false)
    ->LIA_CODE_TO('varchar', 30, '', false)
    ->ID_LIAISON_TO('varchar', 30, '', false)
    ->LIA_ORDRE('int', 11, 'unsigned', false, 0)
    ->LIA_TYPE('varchar', 255, '', false)
    ->LIA_TEMP('varchar', 255, '', false)
    ->LIA_TEXT('varchar', 255, '', true, null)
    ->primary('PRIMARY', 'ID_LIAISON_EXTERNE')
    ->index('LIA_CODE_TO', 'btree', 'LIA_CODE_TO')
    ->index('LIA_CODE_FROM', 'btree', 'LIA_CODE_FROM')
    ->index('ID_LIAISON_TO', 'btree', 'ID_LIAISON_TO')
    ->index('ID_LIAISON_FROM', 'btree', 'ID_LIAISON_FROM')
    ->reference('LIAISON_EXTERNE_LIA_CODE_TO', 'LIA_CODE_TO', 'DD_LIAISON', 'LIA_CODE')
    ->reference('LIAISON_EXTERNE_LIA_CODE_FROM', 'LIA_CODE_FROM', 'DD_LIAISON', 'LIA_CODE');

$_s->LIAISON_PAGE->ID_LIAISON_PAGE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->LIA_CODE('varchar', 30, '', false)
    ->ID_LIAISON('varchar', 32, '', false)
    ->ID_PAGE('int', 11, 'unsigned', false)
    ->ID_PARAGRAPHE('int', 11, 'unsigned')
    ->ID_REVISION('int', 11, 'unsigned')
    ->LIA_ORDRE('int', 11, 'unsigned', false, 0)
    ->LIA_TYPE('varchar', 255, '', false)
    ->LIA_TEMP('varchar', 255, '', false)
    ->LIA_TEXT('varchar', 255, '', true, null)
    ->primary('PRIMARY', 'ID_LIAISON_PAGE')
    ->index('ID_PARAGRAPHE', 'btree', 'ID_PARAGRAPHE')
    ->index('LIA_CODE', 'btree', 'LIA_CODE')
    ->index('ID_LIAISON', 'btree', 'ID_LIAISON')
    ->index('ID_PAGE', 'btree', 'ID_PAGE')
    ->index('ID_REVISION', 'btree', 'ID_REVISION')
    ->reference('LIAISON_PAGE_LIA_CODE', 'LIA_CODE', 'DD_LIAISON', 'LIA_CODE')
    ->reference('LIAISON_PAGE_ID_PAGE', 'ID_PAGE', 'OFF_PAGE', 'ID_PAGE');

$_s->LIAISON_THEMATIQUE->ID_LIAISON_THEMATIQUE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->LIA_CODE('varchar', 30, '', false)
    ->ID_LIAISON('int', 11, 'unsigned', false)
    ->ID_THEMATIQUE('int', 11, 'unsigned', false)
    ->primary('PRIMARY', 'ID_LIAISON_THEMATIQUE')
    ->index('ID_LIAISON', 'btree', 'ID_LIAISON')
    ->index('ID_THEMATIQUE', 'btree', 'ID_THEMATIQUE')
    ->index('LIA_CODE', 'btree', 'LIA_CODE')
    ->reference('LIAISON_THEMATIQUE_ibfk_1', 'LIA_CODE', 'DD_LIAISON', 'LIA_CODE')
    ->reference('LIAISON_THEMATIQUE_ibfk_2', 'ID_THEMATIQUE', 'THEMATIQUE', 'ID_THEMATIQUE');

$_s->LIAISON_UTILISATEUR->ID_LIAISON_UTILISATEUR('int', 11, 'unsigned', false, false, 'auto_increment')
    ->LIA_CODE('varchar', 30, '', false)
    ->ID_LIAISON('int', 11, 'unsigned', false)
    ->ID_UTILISATEUR('int', 11, 'unsigned', false)
    ->ID_REVISION('int', 11, 'unsigned')
    ->LIA_ORDRE('int', 11, 'unsigned', false, 0)
    ->LIA_TYPE('varchar', 255, '', false)
    ->LIA_TEMP('varchar', 255, '', false)
    ->LIA_TEXT('varchar', 255, '', true, null)
    ->primary('PRIMARY', 'ID_LIAISON_UTILISATEUR')
    ->index('ID_LIAISON', 'btree', 'ID_LIAISON')
    ->index('ID_UTILISATEUR', 'btree', 'ID_UTILISATEUR')
    ->index('LIA_CODE', 'btree', 'LIA_CODE')
    ->index('ID_REVISION', 'btree', 'ID_REVISION')
    ->reference('LIAISON_UTILISATEUR_ibfk_1', 'LIA_CODE', 'DD_LIAISON', 'LIA_CODE')
    ->reference('LIAISON_UTILISATEUR_ibfk_2', 'ID_UTILISATEUR', 'UTILISATEUR', 'ID_UTILISATEUR')
    ->reference('LIAISON_UTILISATEUR_ID_REVISION', 'ID_REVISION', 'REVISION', 'ID_REVISION');

$_s->LIAISON_WEBOTHEQUE->ID_LIAISON_WEBOTHEQUE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->LIA_CODE('varchar', 30, '', false)
    ->ID_LIAISON('varchar', 32, '', false)
    ->ID_WEBOTHEQUE('int', 11, 'unsigned', false)
    ->ID_REVISION('int', 11, 'unsigned')
    ->LIA_ORDRE('int', 11, 'unsigned', false, 0)
    ->LIA_TYPE('varchar', 255, '', false)
    ->LIA_TEMP('varchar', 255, '', false)
    ->LIA_TEXT('varchar', 255, '', true, null)
    ->primary('PRIMARY', 'ID_LIAISON_WEBOTHEQUE')
    ->index('ID_WEBOTHEQUE', 'btree', 'ID_WEBOTHEQUE')
    ->index('LIA_CODE', 'btree', 'LIA_CODE')
    ->index('ID_REVISION', 'btree', 'ID_REVISION')
    ->reference('LIAISON_WEBOTHEQUE_LIA_CODE', 'LIA_CODE', 'DD_LIAISON', 'LIA_CODE')
    ->reference('LIAISON_WEBOTHEQUE_ID_WEBOTHEQUE', 'ID_WEBOTHEQUE', 'WEBOTHEQUE', 'ID_WEBOTHEQUE')
    ->reference('LIAISON_WEBOTHEQUE_ID_REVISION', 'ID_REVISION', 'REVISION', 'ID_REVISION');

$_s->MODULE_PROFIL->MOD_CODE('varchar', 30, '', false)
    ->PRO_CODE('varchar', 30, '', false)
    ->primary('PRIMARY', 'MOD_CODE', 'PRO_CODE')
    ->index('PRO_CODE', 'btree', 'PRO_CODE')
    ->reference('MODULE_PROFIL_ibfk_2', 'PRO_CODE', 'DD_PROFIL', 'PRO_CODE')
    ->reference('MODULE_PROFIL_ibfk_1', 'MOD_CODE', 'DD_MODULE', 'MOD_CODE');

$_s->OFF_PAGE->ID_PAGE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->ID_UTILISATEURVERROU('int', 11, 'unsigned')
    ->ID_WEBOTHEQUE_IMAGE('int', 11, 'unsigned')
    ->ID_WEBOTHEQUE_LIENEXTERNE('int', 11, 'unsigned')
    ->ID_PAGE_REDIRECT('int', 11, 'unsigned')
    ->ID_PAGE_CANONICAL('int', 11, 'unsigned')
    ->ID_STYLEDYNAMIQUE('int', 11, 'unsigned')
    ->PST_CODE('varchar', 30, '', false)
    ->PGS_CODE('varchar', 30)
    ->PSS_CODE('varchar', 30)
    ->PAG_IDPERE('int', 11, 'unsigned')
    ->PAG_TITRE('varchar', 255)
    ->PAG_TITRE_MENU('varchar', 255)
    ->PAG_TITRE_REFERENCEMENT('varchar', 255)
    ->PAG_TITLE('varchar', 255)
    ->PAG_ACCROCHE('text')
    ->PAG_METADESCRIPTION('text')
    ->PAG_HEAD('text')
    ->PAG_POIDS('int', 6, 'unsigned')
    ->PAG_VISIBLE_MENU('tinyint', 1, 'unsigned', false, 1)
    ->PAG_MOTCLE1('varchar', 255)
    ->PAG_MOTCLE2('varchar', 255)
    ->PAG_MOTCLE3('varchar', 255)
    ->PAG_MOTCLE4('varchar', 255)
    ->PAG_MOTCLE5('varchar', 255)
    ->PAG_DATEONLINE('int', 11, 'unsigned')
    ->PAG_DATEONLINE_ON('int', 11, 'unsigned')
    ->PAG_DATEOFFLINE('int', 11, 'unsigned')
    ->PAG_DATEOFFLINE_ON('int', 11, 'unsigned')
    ->PAG_DATEVERROU('int', 11, 'unsigned')
    ->PAG_DATEMODIFICATION('int', 11, 'unsigned')
    ->PAG_DATEMISEAJOUR('int', 11, 'unsigned')
    ->PAG_URLREWRITING('varchar', 255)
    ->PAG_GOOGLEFREQUENCE('varchar', 255)
    ->PAG_GOOGLEPRIORITE('varchar', 255)
    ->PAG_EXCLURECHERCHE('tinyint', 1, 'unsigned', false, 0)
    ->PAG_NOINDEX('tinyint', 1, 'unsigned', false, 0)
    ->PAG_MASQUERGAUCHE('tinyint', 1, 'unsigned', false, 0)
    ->PAG_MASQUERDROITE('tinyint', 1, 'unsigned', false, 0)
    ->PAG_STYLEDEFAUTHERITABLE('tinyint', 1, 'unsigned', false, 0)
    ->PAG_STYLEPERSOHERITABLE('tinyint', 1, 'unsigned', false, 0)
    ->PAG_COMMENTAIREACTIF('tinyint', 1, 'unsigned', false, 0)
    ->PAG_HTTPS('tinyint', 1, 'unsigned', false, 0)
    ->PAG_CACHE('tinyint', 1, 'unsigned', false, 1)
    ->primary('PRIMARY', 'ID_PAGE')
    ->index('PAG_IDPERE', 'btree', 'PAG_IDPERE')
    ->index('PST_CODE', 'btree', 'PST_CODE')
    ->index('PGS_CODE', 'btree', 'PGS_CODE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('PSS_CODE', 'btree', 'PSS_CODE')
    ->index('ID_UTILISATEURVERROU', 'btree', 'ID_UTILISATEURVERROU')
    ->index('ID_STYLEDYNAMIQUE', 'btree', 'ID_STYLEDYNAMIQUE')
    ->index('ID_WEBOTHEQUE_LIENEXTERNE', 'btree', 'ID_WEBOTHEQUE_LIENEXTERNE')
    ->index('ID_PAGE_REDIRECT', 'btree', 'ID_PAGE_REDIRECT')
    ->index('ID_PAGE_CANONICAL', 'btree', 'ID_PAGE_CANONICAL')
    ->index('ID_WEBOTHEQUE_IMAGE', 'btree', 'ID_WEBOTHEQUE_IMAGE')
    ->reference('OFF_PAGE_ID_WEBOTHEQUE_LIENEXTERNE', 'ID_WEBOTHEQUE_LIENEXTERNE', 'WEBOTHEQUE', 'ID_WEBOTHEQUE')
    ->reference('OFF_PAGE_SIT_CODE', 'SIT_CODE', 'DD_SITE', 'SIT_CODE', 'cascade')
    ->reference('OFF_PAGE_ID_STYLEDYNAMIQUE', 'ID_STYLEDYNAMIQUE', 'STYLEDYNAMIQUE', 'ID_STYLEDYNAMIQUE')
    ->reference('OFF_PAGE_ID_WEBOTHEQUE_IMAGE', 'ID_WEBOTHEQUE_IMAGE', 'WEBOTHEQUE', 'ID_WEBOTHEQUE')
    ->reference('OFF_PAGE_ID_PAGE_REDIRECT', 'ID_PAGE_REDIRECT', 'OFF_PAGE', 'ID_PAGE')
    ->reference('OFF_PAGE_ID_PAGE_CANONICAL', 'ID_PAGE_CANONICAL', 'OFF_PAGE', 'ID_PAGE')
    ->reference('OFF_PAGE_ID_UTILISATEURVERROU', 'ID_UTILISATEURVERROU', 'UTILISATEUR', 'ID_UTILISATEUR')
    ->reference('OFF_PAGE_PST_CODE', 'PST_CODE', 'DD_PAGESTATUT', 'PST_CODE')
    ->reference('OFF_PAGE_PGS_CODE', 'PGS_CODE', 'DD_PAGESPECIALE', 'PGS_CODE')
    ->reference('OFF_PAGE_PSS_CODE', 'PSS_CODE', 'DD_PAGESTYLE', 'PSS_CODE')
    ->reference('OFF_PAGE_PAG_IDPERE', 'PAG_IDPERE', 'OFF_PAGE', 'ID_PAGE');

$_s->OFF_PARAGRAPHE->ID_PARAGRAPHE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_PAGE('int', 11, 'unsigned', false)
    ->PRT_CODE('varchar', 30, '', false)
    ->PRS_CODE('varchar', 30)
    ->PRS_WIDTH('varchar', 30)
    ->TPL_CODE('varchar', 30)
    ->PAR_TPL_IDENTIFIANT('varchar', 255)
    ->PAR_POIDS('int', 6, 'unsigned')
    ->PAR_TITRE('varchar', 255)
    ->PAR_CONTENU('text')
    ->PAR_CONTENUPARSE('text')
    ->PAR_CONTENUTEXTE('text')
    ->PAR_APARSER('tinyint', 1, 'unsigned', false, 1)
    ->PAR_MOBILEHIDDEN('tinyint', 1, 'unsigned', false, 0)
    ->PAR_COLONNE('varchar', 255, '', false)
    ->PAR_HERITABLE('tinyint', 1, 'unsigned', false, 0)
    ->PAR_DATEMODIFICATION('int', 11, 'unsigned')
    ->PAR_BROUILLON('text')
    ->primary('PRIMARY', 'ID_PARAGRAPHE')
    ->index('ID_PAGE', 'btree', 'ID_PAGE')
    ->index('PRT_CODE', 'btree', 'PRT_CODE')
    ->index('TPL_CODE', 'btree', 'TPL_CODE')
    ->index('PRS_CODE', 'btree', 'PRS_CODE')
    ->index('PAR_TPL_IDENTIFIANT', 'btree', 'PAR_TPL_IDENTIFIANT')
    ->reference('OFF_PARAGRAPHE_ibfk_5', 'PRS_CODE', 'DD_PARAGRAPHESTYLE', 'PRS_CODE')
    ->reference('OFF_PARAGRAPHE_ibfk_1', 'ID_PAGE', 'OFF_PAGE', 'ID_PAGE')
    ->reference('OFF_PARAGRAPHE_ibfk_2', 'PRT_CODE', 'DD_PARAGRAPHETYPE', 'PRT_CODE')
    ->reference('OFF_PARAGRAPHE_ibfk_4', 'TPL_CODE', 'DD_TEMPLATE', 'TPL_CODE');

$_s->ON_PAGE->ID_PAGE('int', 11, 'unsigned', false)
    ->SIT_CODE('varchar', 30, '', false)
    ->ID_WEBOTHEQUE_IMAGE('int', 11, 'unsigned')
    ->ID_WEBOTHEQUE_LIENEXTERNE('int', 11, 'unsigned')
    ->ID_PAGE_REDIRECT('int', 11, 'unsigned')
    ->ID_PAGE_CANONICAL('int', 11, 'unsigned')
    ->ID_STYLEDYNAMIQUE('int', 11, 'unsigned')
    ->PGS_CODE('varchar', 30)
    ->PSS_CODE('varchar', 30)
    ->PAG_IDPERE('int', 11, 'unsigned')
    ->PAG_TITRE('varchar', 255)
    ->PAG_TITRE_MENU('varchar', 255)
    ->PAG_TITRE_REFERENCEMENT('varchar', 255)
    ->PAG_TITLE('varchar', 255)
    ->PAG_ACCROCHE('text')
    ->PAG_METADESCRIPTION('text')
    ->PAG_HEAD('text')
    ->PAG_POIDS('int', 6, 'unsigned')
    ->PAG_VISIBLE_MENU('tinyint', 1, 'unsigned', false, 1)
    ->PAG_MOTCLE1('varchar', 255)
    ->PAG_MOTCLE2('varchar', 255)
    ->PAG_MOTCLE3('varchar', 255)
    ->PAG_MOTCLE4('varchar', 255)
    ->PAG_MOTCLE5('varchar', 255)
    ->PAG_DATEMODIFICATION('int', 11, 'unsigned')
    ->PAG_DATEMISEAJOUR('int', 11, 'unsigned')
    ->PAG_DATEMISEENLIGNE('int', 11, 'unsigned')
    ->PAG_URLREWRITING('varchar', 255)
    ->PAG_GOOGLEFREQUENCE('varchar', 255)
    ->PAG_GOOGLEPRIORITE('varchar', 255)
    ->PAG_EXCLURECHERCHE('tinyint', 1, 'unsigned', false, 0)
    ->PAG_NOINDEX('tinyint', 1, 'unsigned', false, 0)
    ->PAG_MASQUERGAUCHE('tinyint', 1, 'unsigned', false, 0)
    ->PAG_MASQUERDROITE('tinyint', 1, 'unsigned', false, 0)
    ->PAG_COMMENTAIREACTIF('tinyint', 1, 'unsigned', false, 0)
    ->PAG_HTTPS('tinyint', 1, 'unsigned', false, 0)
    ->PAG_CACHE('tinyint', 1, 'unsigned', false, 1)
    ->primary('PRIMARY', 'ID_PAGE')
    ->index('PGS_CODE', 'btree', 'PGS_CODE')
    ->index('PAG_IDPERE', 'btree', 'PAG_IDPERE')
    ->index('ID_WEBOTHEQUE_LIENEXTERNE', 'btree', 'ID_WEBOTHEQUE_LIENEXTERNE')
    ->index('ID_PAGE_REDIRECT', 'btree', 'ID_PAGE_REDIRECT')
    ->index('ID_PAGE_CANONICAL', 'btree', 'ID_PAGE_CANONICAL')
    ->index('ID_WEBOTHEQUE_IMAGE', 'btree', 'ID_WEBOTHEQUE_IMAGE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('PSS_CODE', 'btree', 'PSS_CODE')
    ->index('ID_STYLEDYNAMIQUE', 'btree', 'ID_STYLEDYNAMIQUE')
    ->reference('ON_PAGE_ID_WEBOTHEQUE_LIENEXTERNE', 'ID_WEBOTHEQUE_LIENEXTERNE', 'WEBOTHEQUE', 'ID_WEBOTHEQUE')
    ->reference('ON_PAGE_SIT_CODE', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('ON_PAGE_ID_PAGE_REDIRECT', 'ID_PAGE_REDIRECT', 'OFF_PAGE', 'ID_PAGE')
    ->reference('ON_PAGE_ID_PAGE_CANONICAL', 'ID_PAGE_CANONICAL', 'OFF_PAGE', 'ID_PAGE')
    ->reference('ON_PAGE_DD_PAGESPECIALE', 'PGS_CODE', 'DD_PAGESPECIALE', 'PGS_CODE')
    ->reference('ON_PAGE_DD_PAGESTYLE', 'PSS_CODE', 'DD_PAGESTYLE', 'PSS_CODE')
    ->reference('ON_PAGE_PAG_IDPERE', 'PAG_IDPERE', 'OFF_PAGE', 'ID_PAGE')
    ->reference('ON_PAGE_ID_STYLEDYNAMIQUE', 'ID_STYLEDYNAMIQUE', 'STYLEDYNAMIQUE', 'ID_STYLEDYNAMIQUE')
    ->reference('ON_PAGE_ID_WEBOTHEQUE_IMAGE', 'ID_WEBOTHEQUE_IMAGE', 'WEBOTHEQUE', 'ID_WEBOTHEQUE');

$_s->ON_PARAGRAPHE->ID_PARAGRAPHE('int', 11, 'unsigned', false)
    ->ID_PAGE('int', 11, 'unsigned', false)
    ->PRT_CODE('varchar', 30, '', false)
    ->PRS_CODE('varchar', 30)
    ->PRS_WIDTH('varchar', 30)
    ->TPL_CODE('varchar', 30)
    ->PAR_TPL_IDENTIFIANT('varchar', 255)
    ->PAR_POIDS('int', 6, 'unsigned')
    ->PAR_TITRE('varchar', 255)
    ->PAR_CONTENU('text')
    ->PAR_CONTENUPARSE('text')
    ->PAR_CONTENUTEXTE('text')
    ->PAR_APARSER('tinyint', 1, 'unsigned', false, 1)
    ->PAR_MOBILEHIDDEN('tinyint', 1, 'unsigned', false, 0)
    ->PAR_COLONNE('varchar', 255, '', false)
    ->PAR_HERITABLE('tinyint', 1, 'unsigned', false, 0)
    ->primary('PRIMARY', 'ID_PARAGRAPHE')
    ->index('ID_PAGE', 'btree', 'ID_PAGE')
    ->index('PRT_CODE', 'btree', 'PRT_CODE')
    ->index('TPL_CODE', 'btree', 'TPL_CODE')
    ->index('PRS_CODE', 'btree', 'PRS_CODE')
    ->index('PAR_TPL_IDENTIFIANT', 'btree', 'PAR_TPL_IDENTIFIANT')
    ->reference('ON_PARAGRAPHE_ibfk_5', 'PRS_CODE', 'DD_PARAGRAPHESTYLE', 'PRS_CODE')
    ->reference('ON_PARAGRAPHE_ibfk_1', 'ID_PAGE', 'ON_PAGE', 'ID_PAGE')
    ->reference('ON_PARAGRAPHE_ibfk_2', 'PRT_CODE', 'DD_PARAGRAPHETYPE', 'PRT_CODE')
    ->reference('ON_PARAGRAPHE_ibfk_4', 'TPL_CODE', 'DD_TEMPLATE', 'TPL_CODE');

$_s->RECHERCHEREFERENCEMENT->ID_RECHERCHEREFERENCEMENT('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->REC_TITLE('varchar', 255, '', false)
    ->REC_EXPRESSION('varchar', 255, '', false)
    ->REC_RESUME('varchar', 255, '', false)
    ->REC_DESCRIPTION('text', '', '', false)
    ->REC_GOOGLEPRIORITE('varchar', 255, '', false)
    ->REC_GOOGLEFREQUENCE('varchar', 255, '', false)
    ->REC_GOOGLELASTMOD('int', 11, 'unsigned', '', false)
    ->primary('PRIMARY', 'ID_RECHERCHEREFERENCEMENT')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->reference('RECHERCHEREFERENCEMENT_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');

$_s->REVISION->ID_REVISION('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_PAGE('int', 11, 'unsigned', false)
    ->REV_DATECREATION('int', 11, 'unsigned')
    ->primary('PRIMARY', 'ID_REVISION')
    ->index('ID_PAGE', 'btree', 'ID_PAGE');

$_s->REVISION_GROUPE->ID_GROUPE('int', 11, 'unsigned', false)
    ->ID_REVISION('int', 11, 'unsigned', false)
    ->primary('PRIMARY', 'ID_GROUPE', 'ID_REVISION')
    ->index('ID_REVISION', 'btree', 'ID_REVISION')
    ->reference('REVISION_GROUPE_ibfk_2', 'ID_REVISION', 'REVISION', 'ID_REVISION')
    ->reference('REVISION_GROUPE_ibfk_1', 'ID_GROUPE', 'GROUPE', 'ID_GROUPE');

$_s->REVISION_PAGE->ID_REVISIONPAGE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_REVISION('int', 11, 'unsigned', false)
    ->ID_PAGE('int', 11, 'unsigned', false)
    ->SIT_CODE('varchar', 30, '', false)
    ->ID_PAGE_REDIRECT('int', 11, 'unsigned')
    ->ID_WEBOTHEQUE_IMAGE('int', 11, 'unsigned')
    ->ID_WEBOTHEQUE_LIENEXTERNE('int', 11, 'unsigned')
    ->PGS_CODE('varchar', 30)
    ->PSS_CODE('varchar', 30)
    ->ID_STYLEDYNAMIQUE('int', 11, 'unsigned')
    ->PAG_TITRE('varchar', 255)
    ->PAG_TITRE_MENU('varchar', 255)
    ->PAG_TITRE_REFERENCEMENT('varchar', 255)
    ->PAG_TITLE('varchar', 255)
    ->PAG_ACCROCHE('text')
    ->PAG_METADESCRIPTION('text')
    ->PAG_HEAD('text')
    ->PAG_VISIBLE_MENU('tinyint', 1, 'unsigned', false, 1)
    ->PAG_MOTCLE1('varchar', 255)
    ->PAG_MOTCLE2('varchar', 255)
    ->PAG_MOTCLE3('varchar', 255)
    ->PAG_MOTCLE4('varchar', 255)
    ->PAG_MOTCLE5('varchar', 255)
    ->PAG_DATEREVISION('int', 11, 'unsigned')
    ->PAG_DATEMISEAJOUR('int', 11, 'unsigned')
    ->PAG_URLREWRITING('varchar', 255)
    ->PAG_GOOGLEFREQUENCE('varchar', 255)
    ->PAG_GOOGLEPRIORITE('varchar', 255)
    ->PAG_EXCLURECHERCHE('tinyint', 1, 'unsigned', false, 0)
    ->PAG_MASQUERGAUCHE('tinyint', 1, 'unsigned', false, 0)
    ->PAG_MASQUERDROITE('tinyint', 1, 'unsigned', false, 0)
    ->PAG_COMMENTAIREACTIF('tinyint', 1, 'unsigned', false, 1)
    ->PAG_HTTPS('tinyint', 1, 'unsigned', false, 0)
    ->PAG_CACHE('tinyint', 1, 'unsigned', false, 1)
    ->primary('PRIMARY', 'ID_REVISIONPAGE')
    ->index('PGS_CODE', 'btree', 'PGS_CODE')
    ->index('ID_WEBOTHEQUEACCROCHE', 'btree', 'ID_WEBOTHEQUE_IMAGE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_PAGE', 'btree', 'ID_PAGE')
    ->index('ID_REVISION', 'btree', 'ID_REVISION')
    ->index('ID_PAGE_REDIRECT', 'btree', 'ID_PAGE_REDIRECT')
    ->index('ID_WEBOTHEQUE_LIENEXTERNE', 'btree', 'ID_WEBOTHEQUE_LIENEXTERNE')
    ->index('PSS_CODE', 'btree', 'PSS_CODE')
    ->index('ID_STYLEDYNAMIQUE', 'btree', 'ID_STYLEDYNAMIQUE')
    ->reference('REVISION_PAGE_ibfk_8', 'ID_PAGE', 'OFF_PAGE', 'ID_PAGE')
    ->reference('REVISION_PAGE_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('REVISION_PAGE_ibfk_5', 'PGS_CODE', 'DD_PAGESPECIALE', 'PGS_CODE')
    ->reference('REVISION_PAGE_ibfk_6', 'ID_WEBOTHEQUE_IMAGE', 'WEBOTHEQUE', 'ID_WEBOTHEQUE')
    ->reference('REVISION_PAGE_ibfk_7', 'ID_REVISION', 'REVISION', 'ID_REVISION')
    ->reference('REVISION_PAGE_WEBOTHEQUE_LIEN', 'ID_WEBOTHEQUE_LIENEXTERNE', 'WEBOTHEQUE', 'ID_WEBOTHEQUE')
    ->reference('REVISION_PAGE_PAGE_REDIRECT', 'ID_PAGE_REDIRECT', 'OFF_PAGE', 'ID_PAGE')
    ->reference('REVISION_PAGE_PAGE_STYLE', 'PSS_CODE', 'DD_PAGESTYLE', 'PSS_CODE')
    ->reference('REVISION_PAGE_STYLEDYNAMIQUE', 'ID_STYLEDYNAMIQUE', 'STYLEDYNAMIQUE', 'ID_STYLEDYNAMIQUE');

$_s->REVISION_PARAGRAPHE->ID_REVISIONPARAGRAPHE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_REVISION('int', 11, 'unsigned', false)
    ->ID_PARAGRAPHE('int', 11, 'unsigned', false)
    ->ID_PAGE('int', 11, 'unsigned', false)
    ->PRT_CODE('varchar', 30, '', false)
    ->PRS_CODE('varchar', 30)
    ->PRS_WIDTH('varchar', 30)
    ->TPL_CODE('varchar', 30)
    ->PAR_TPL_IDENTIFIANT('varchar', 255)
    ->PAR_POIDS('int', 6, 'unsigned')
    ->PAR_TITRE('varchar', 255)
    ->PAR_CONTENU('text')
    ->PAR_CONTENUPARSE('text')
    ->PAR_CONTENUTEXTE('text')
    ->PAR_APARSER('tinyint', 1, 'unsigned', false, 1)
    ->PAR_MOBILEHIDDEN('tinyint', 1, 'unsigned', false, 0)
    ->PAR_COLONNE('varchar', 255, '', false)
    ->PAR_HERITABLE('tinyint', 1, 'unsigned', false, 0)
    ->PAR_BROUILLON('text')
    ->primary('PRIMARY', 'ID_REVISIONPARAGRAPHE')
    ->index('ID_PAGE', 'btree', 'ID_PAGE')
    ->index('PRT_CODE', 'btree', 'PRT_CODE')
    ->index('TPL_CODE', 'btree', 'TPL_CODE')
    ->index('PRS_CODE', 'btree', 'PRS_CODE')
    ->index('PAR_TPL_IDENTIFIANT', 'btree', 'PAR_TPL_IDENTIFIANT')
    ->index('ID_REVISION', 'btree', 'ID_REVISION')
    ->index('ID_PARAGRAPHE', 'btree', 'ID_PARAGRAPHE')
    ->reference('REVISION_PARAGRAPHE_ibfk_2', 'PRT_CODE', 'DD_PARAGRAPHETYPE', 'PRT_CODE')
    ->reference('REVISION_PARAGRAPHE_ibfk_3', 'PRS_CODE', 'DD_PARAGRAPHESTYLE', 'PRS_CODE')
    ->reference('REVISION_PARAGRAPHE_ibfk_4', 'TPL_CODE', 'DD_TEMPLATE', 'TPL_CODE')
    ->reference('REVISION_PARAGRAPHE_ibfk_5', 'ID_REVISION', 'REVISION', 'ID_REVISION')
    ->reference('REVISION_PARAGRAPHE_ibfk_6', 'ID_PAGE', 'OFF_PAGE', 'ID_PAGE');

$_s->REVISION_ROLE->ID_ROLE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30)
    ->ID_UTILISATEUR('int', 11, 'unsigned')
    ->PRO_CODE('varchar', 30, '', false)
    ->ID_REVISION('int', 11, 'unsigned')
    ->primary('PRIMARY', 'ID_ROLE')
    ->index('PRO_CODE', 'btree', 'PRO_CODE')
    ->index('ID_REVISION', 'btree', 'ID_REVISION')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_UTILISATEUR', 'btree', 'ID_UTILISATEUR')
    ->reference('REVISION_ROLE_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('REVISION_ROLE_ibfk_3', 'PRO_CODE', 'DD_PROFIL', 'PRO_CODE')
    ->reference('REVISION_ROLE_ibfk_4', 'ID_REVISION', 'REVISION', 'ID_REVISION')
    ->reference('REVISION_ROLE_ibfk_9', 'ID_UTILISATEUR', 'UTILISATEUR', 'ID_UTILISATEUR');

$_s->ROLE->ID_ROLE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30)
    ->ID_UTILISATEUR('int', 11, 'unsigned')
    ->PRO_CODE('varchar', 30, '', false)
    ->ID_PAGE('int', 11, 'unsigned')
    ->primary('PRIMARY', 'ID_ROLE')
    ->index('PRO_CODE', 'btree', 'PRO_CODE')
    ->index('ID_PAGE', 'btree', 'ID_PAGE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_UTILISATEUR', 'btree', 'ID_UTILISATEUR')
    ->reference('ROLE_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('ROLE_ibfk_3', 'PRO_CODE', 'DD_PROFIL', 'PRO_CODE')
    ->reference('ROLE_ibfk_4', 'ID_PAGE', 'OFF_PAGE', 'ID_PAGE')
    ->reference('ROLE_ibfk_6', 'ID_UTILISATEUR', 'UTILISATEUR', 'ID_UTILISATEUR');

$_s->SITE_MODULE->SIT_CODE('varchar', 30, '', false)
    ->MOD_CODE('varchar', 30, '', false)
    ->primary('PRIMARY', 'SIT_CODE', 'MOD_CODE')
    ->index('MOD_CODE', 'btree', 'MOD_CODE')
    ->reference('SITE_MODULE_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('SITE_MODULE_ibfk_2', 'MOD_CODE', 'DD_MODULE', 'MOD_CODE');

$_s->SITE_PARTAGE->SIT_CODE_FROM('varchar', 30, '', false)
    ->SIT_CODE_TO('varchar', 30, '', false)
    ->primary('PRIMARY', 'SIT_CODE_FROM', 'SIT_CODE_TO')
    ->index('SIT_CODE_TO', 'btree', 'SIT_CODE_TO')
    ->reference('SITE_PARTAGE_ibfk_2', 'SIT_CODE_TO', 'DD_SITE', 'SIT_CODE')
    ->reference('SITE_PARTAGE_ibfk_1', 'SIT_CODE_FROM', 'DD_SITE', 'SIT_CODE');

$_s->STOPWORD_LANGUE->STP_LIBELLE('varchar', 255, '', false)
    ->LNG_CODE('varchar', 30, '', false)
    ->primary('PRIMARY', 'STP_LIBELLE', 'LNG_CODE')
    ->index('LNG_CODE', 'btree', 'LNG_CODE')
    ->reference('STOPWORD_LANGUE_ibfk_1', 'LNG_CODE', 'DD_LANGUE', 'LNG_CODE');

$_s->STOPWORD_SITE->STP_LIBELLE('varchar', 255, '', false)
    ->SIT_CODE('varchar', 30, '', false)
    ->primary('PRIMARY', 'STP_LIBELLE', 'SIT_CODE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->reference('STOPWORD_SITE_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');

$_s->STYLEDYNAMIQUE->ID_STYLEDYNAMIQUE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->STY_LIBELLE('varchar', 255, '', false)
    ->STY_CSS('text', 0, '', false)
    ->primary('PRIMARY', 'ID_STYLEDYNAMIQUE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->reference('STYLEDYNAMIQUE_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');

$_s->THEMATIQUE->ID_THEMATIQUE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->THE_LIBELLE('varchar', 255)
    ->primary('PRIMARY', 'ID_THEMATIQUE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->reference('THEMATIQUE_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');

$_s->TRADUCTION_LANGUE->TRA_CODE('varchar', 255, '', false)
    ->LNG_CODE('varchar', 30, '', false)
    ->TRA_LIBELLE('varchar', 255)
    ->primary('PRIMARY', 'TRA_CODE', 'LNG_CODE')
    ->index('LNG_CODE', 'btree', 'LNG_CODE')
    ->reference('TRADUCTION_LANGUE_ibfk_2', 'LNG_CODE', 'DD_LANGUE', 'LNG_CODE')
    ->reference('TRADUCTION_LANGUE_ibfk_1', 'TRA_CODE', 'DD_TRADUCTION', 'TRA_CODE');

$_s->TRADUCTION_SITE->TRA_CODE('varchar', 255, '', false)
    ->SIT_CODE('varchar', 30, '', false)
    ->TRA_LIBELLE('varchar', 255)
    ->primary('PRIMARY', 'TRA_CODE', 'SIT_CODE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->reference('TRADUCTION_SITE_ibfk_2', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('TRADUCTION_SITE_ibfk_1', 'TRA_CODE', 'DD_TRADUCTION', 'TRA_CODE');

$_s->URLALTERNATIVE->ID_PAGE('int', 11, 'unsigned', false)
    ->URA_LIBELLE('varchar', 255, '', false)
    ->primary('PRIMARY', 'ID_PAGE', 'URA_LIBELLE')
    ->reference('URLALTERNATIVE_ibfk_1', 'ID_PAGE', 'OFF_PAGE', 'ID_PAGE');

$_s->UTILISATEUR->ID_UTILISATEUR('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_LDAP('int', 11, 'unsigned')
    ->SIT_CODE('varchar', 30, '', false)
    ->LNG_CODE('varchar', 10, '', false, 'fr_FR')
    ->ID_PAGE('int', 11, 'unsigned')
    ->UTI_CIVILITE('varchar', 255)
    ->UTI_NOM('varchar', 255)
    ->UTI_PRENOM('varchar', 255)
    ->UTI_EMAIL('varchar', 255)
    ->UTI_LOGIN('varchar', 255)
    ->UTI_PASSWORD('varchar', 255)
    ->UTI_FONCTION('varchar', 255)
    ->UTI_TELEPHONE('varchar', 255)
    ->UTI_ORGANISME('varchar', 255)
    ->UTI_ADRESSE('text')
    ->UTI_CODEPOSTAL('varchar', 255)
    ->UTI_VILLE('varchar', 255)
    ->UTI_PAYS('varchar', 255)
    ->UTI_FAX('varchar', 255)
    ->UTI_DATECREATION('int', 11, 'unsigned')
    ->UTI_DATEMODIFICATION('int', 11, 'unsigned')
    ->UTI_PRELASTCONNEXION('int', 11, 'unsigned')
    ->UTI_LASTCONNEXION('int', 11, 'unsigned')
    ->UTI_STATUT_LOCKED('tinyint', 1, 'unsigned', false, 0)
    ->UTI_STATUT_BLOCKED('tinyint', 1, 'unsigned', false, 0)
    ->UTI_PWD_MUSTBECHANGED('tinyint', 1, 'unsigned', false, 0)
    ->UTI_AUTH_INFO('varchar', 500)
    ->primary('PRIMARY', 'ID_UTILISATEUR')
    ->unique('UTI_LOGIN', 'UTI_LOGIN')
    ->index('ID_LDAP', 'btree', 'ID_LDAP')
    ->index('LNG_CODE', 'btree', 'LNG_CODE')
    ->index('ID_PAGE', 'btree', 'ID_PAGE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('UTI_AUTH_INFO', 'btree', 'UTI_AUTH_INFO')
    ->reference('UTILISATEUR_LDAP_ibfk', 'ID_LDAP', 'LDAP', 'ID_LDAP')
    ->reference('UTILISATEUR_ibfk_3', 'ID_PAGE', 'OFF_PAGE', 'ID_PAGE')
    ->reference('UTILISATEUR_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('UTILISATEUR_ibfk_2', 'LNG_CODE', 'DD_LANGUE', 'LNG_CODE');

$_s->WEBOTHEQUE->ID_WEBOTHEQUE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_WEBOTHEQUECATEGORIE('int', 11, 'unsigned')
    ->SIT_CODE('varchar', 30, '', false)
    ->ID_UTILISATEUR('int', 11, 'unsigned')
    ->WBT_CODE('varchar', 30, '', false)
    ->WEB_LIBELLE('varchar', 255, '', false)
    ->WEB_CHEMIN('varchar', 255, '', false)
    ->WEB_CHEMINACC('varchar', 255, '', false)
    ->WEB_VIGNETTE('varchar', 255, '', false)
    ->WEB_DESCRIPTION('text', 0, '', false)
    ->WEB_DESCRIPTIONACC('text', 0, '', false)
    ->WEB_TAILLE('int', 6, 'unsigned')
    ->WEB_TAILLEACC('int', 6, 'unsigned')
    ->WEB_CREDIT('varchar', 255, '', false)
    ->WEB_SOUSTITRE('varchar', 255, '', false)
    ->WEB_AUDIODESCRIPTION('varchar', 255, '', false)
    ->WEB_HAUTEUR('int', 6, 'unsigned')
    ->WEB_LARGEUR('int', 6, 'unsigned')
    ->WEB_DATECREATION('int', 11, 'unsigned', false)
    ->WEB_DATEMODIFICATION('int', 11, 'unsigned', false)
    ->WEB_REDACTEUR('varchar', 255, '', false)
    ->WEB_MD5('char', 32, '', false)
    ->WEB_CHEMINMP4('varchar', 255, '', false)
    ->WEB_CHEMINWEBM('varchar', 255, '', false)
    ->primary('PRIMARY', 'ID_WEBOTHEQUE')
    ->index('WBT_CODE', 'btree', 'WBT_CODE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_WEBOTHEQUECATEGORIE', 'btree', 'ID_WEBOTHEQUECATEGORIE')
    ->index('ID_UTILISATEUR', 'btree', 'ID_UTILISATEUR')
    ->reference('WEBOTHEQUE_ibfk_1', 'ID_WEBOTHEQUECATEGORIE', 'WEBOTHEQUECATEGORIE', 'ID_WEBOTHEQUECATEGORIE')
    ->reference('WEBOTHEQUE_ibfk_2', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('WEBOTHEQUE_ibfk_3', 'ID_UTILISATEUR', 'UTILISATEUR', 'ID_UTILISATEUR')
    ->reference('WEBOTHEQUE_ibfk_4', 'WBT_CODE', 'DD_WEBOTHEQUETYPE', 'WBT_CODE');

$_s->WEBOTHEQUECATEGORIE->ID_WEBOTHEQUECATEGORIE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->WBT_CODE('varchar', 30, '', false)
    ->CAT_IDPARENT('int', 11, 'unsigned')
    ->CAT_LIBELLE('varchar', 255)
    ->primary('PRIMARY', 'ID_WEBOTHEQUECATEGORIE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('WBT_CODE', 'btree', 'WBT_CODE')
    ->index('CAT_IDPARENT', 'btree', 'CAT_IDPARENT')
    ->reference('WEBOTHEQUECATEGORIE_ibfk_1', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('WEBOTHEQUECATEGORIE_ibfk_2', 'WBT_CODE', 'DD_WEBOTHEQUETYPE', 'WBT_CODE')
    ->reference('WEBOTHEQUECATEGORIE_ibfk_3', 'CAT_IDPARENT', 'WEBOTHEQUECATEGORIE', 'ID_WEBOTHEQUECATEGORIE');

$_s->WEBOTHEQUEINDEXER->ID_WEBOTHEQUE('int', 11, 'unsigned', false)
    ->IND_TEXTE('mediumtext')
    ->primary('PRIMARY', 'ID_WEBOTHEQUE')
    ->reference('WEBOTHEQUEINDEXER_ibfk_1', 'ID_WEBOTHEQUE', 'WEBOTHEQUE', 'ID_WEBOTHEQUE');

$_s->WORKFLOW->ID_WORKFLOW('int', 11, 'unsigned', false, false, 'auto_increment')
    ->PST_CODE_IN('varchar', 30, '', false)
    ->PST_CODE_OUT('varchar', 30, '', false)
    ->WKF_LIBELLE('varchar', 255)
    ->WKF_PROFIL('varchar', 255)
    ->WKF_POIDS('int', 6, 'unsigned')
    ->WKF_PRE_FONCTION('varchar', 255)
    ->WKF_POST_FONCTION('varchar', 255)
    ->WKF_CRONABLE('tinyint', 1, 'unsigned', false, 0)
    ->primary('PRIMARY', 'ID_WORKFLOW')
    ->index('PST_CODE_IN', 'btree', 'PST_CODE_IN')
    ->index('PST_CODE_OUT', 'btree', 'PST_CODE_OUT')
    ->reference('WORKFLOW_ibfk_1', 'PST_CODE_IN', 'DD_PAGESTATUT', 'PST_CODE')
    ->reference('WORKFLOW_ibfk_2', 'PST_CODE_OUT', 'DD_PAGESTATUT', 'PST_CODE');

$_s->CAPTCHA->ID_CAPTCHA('varchar', 40, '', false)
    ->CAP_DATE('int', 11, '', false)
    ->CAP_REPONSE('varchar', 30, '', false)
    ->primary('PRIMARY', 'ID_CAPTCHA');

$_s->COMMENTAIRE_PARAM->ID_COMMENTAIRE_PARAM('int', 11, 'unsigned', false, false, 'auto_increment')
    ->SIT_CODE('varchar', 30, '', false)
    ->CPA_TYPEMODERATION('tinyint', 1, 'unsigned', false, 1)
    ->CPA_MES_DEPOT('text', 0, '', false)
    ->CPA_MES_REMERCIEMENT('text', 0, '', false)
    ->CPA_LIBELLELIEN('varchar', 255, '', true)
    ->ID_PAGE('int', 11, 'unsigned', true, null)
    ->CPA_EMAILNOTIFICATION('tinyint', 1, 'unsigned', false, 0)
    ->CPA_SIGNATUREMAIL('text', 0, '', false)
    ->CPA_COMMENTAIREVALIDE('varchar', 255, '', false)
    ->CPA_COMMENTAIREREFUS('varchar', 255, '', false)
    ->CPA_AFFICHAGE_DEFAUT('tinyint', 1, 'unsigned', false, 1)
    ->primary('PRIMARY', 'ID_COMMENTAIRE_PARAM')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_PAGE', 'btree', 'ID_PAGE')
    ->reference('COMMENTAIRE_PARAM_DD_SITE_ibfk', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('COMMENTAIRE_PARAM_OFF_PAGE_ibfk', 'ID_PAGE', 'OFF_PAGE', 'ID_PAGE');

$_s->DD_COMMENTAIRE_LIAISONTYPE->ID_COMMENTAIRE_LIAISONTYPE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->MOD_CODE('varchar', 30, '', false)
    ->PRO_CODE('varchar', 30, '', false)
    ->CLI_CLASSNOM('varchar', 255, '', false)
    ->CLI_CLASSFILE('varchar', 255, '', false)
    ->CLI_CHEMINFICHE('varchar', 255, '', true, null)
    ->primary('PRIMARY', 'ID_COMMENTAIRE_LIAISONTYPE');

$_s->COMMENTAIRE->ID_COMMENTAIRE('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_UTILISATEUR('int', 11, 'unsigned', true)
    ->SIT_CODE('varchar', 30, '', false)
    ->COM_PSEUDO('varchar', 255, '', false)
    ->COM_MESSAGE('text', 0, '', false)
    ->ID_COMMENTAIRE_LIAISONTYPE('int', 11, 'unsigned', false)
    ->COM_IDLIAISON('int', 11, 'unsigned', false)
    ->COM_DATE('int', 11, 'unsigned', false)
    ->COM_ETAT('set(\'VALIDE\',\'REFUS\',\'MODERATION\')', 0, '', false)
    ->COM_MAIL('varchar', 255, '', false)
    ->primary('PRIMARY', 'ID_COMMENTAIRE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('ID_UTILISATEUR', 'btree', 'ID_UTILISATEUR')
    ->index('ID_COMMENTAIRE_LIAISONTYPE', 'btree', 'ID_COMMENTAIRE_LIAISONTYPE')
    ->reference('COMMENTAIRE_DD_SITE_ibfk', 'SIT_CODE', 'DD_SITE', 'SIT_CODE')
    ->reference('COMMENTAIRE_UTILISATEUR_ibfk', 'ID_UTILISATEUR', 'UTILISATEUR', 'ID_UTILISATEUR')
    ->reference('COMMENTAIRE_DD_COMMENTAIRE_LIAISONTYPE_ibfk', 'ID_COMMENTAIRE_LIAISONTYPE', 'DD_COMMENTAIRE_LIAISONTYPE', 'ID_COMMENTAIRE_LIAISONTYPE');
;

$_s->COMMENTAIRE_ABUS->ID_COMMENTAIRE_ABUS('int', 11, 'unsigned', false, false, 'auto_increment')
    ->ID_COMMENTAIRE('int', 11, 'unsigned', false)
    ->ID_UTILISATEUR('int', 11, 'unsigned', true)
    ->CAB_PSEUDO('varchar', 30, '', true)
    ->CAB_MESSAGE('text', 0, '', false)
    ->CAB_DATE('int', 11, 'unsigned', false)
    ->CAB_MAIL('varchar', 255, '', false)
    ->primary('PRIMARY', 'ID_COMMENTAIRE_ABUS')
    ->index('ID_COMMENTAIRE', 'btree', 'ID_COMMENTAIRE')
    ->index('ID_UTILISATEUR', 'btree', 'ID_UTILISATEUR')
    ->reference('COMMENTAIRE_ABUS_COMMENTAIRE_ibfk', 'ID_COMMENTAIRE', 'COMMENTAIRE', 'ID_COMMENTAIRE')
    ->reference('COMMENTAIRE_ABUS_UTILISATEUR_ibfk', 'ID_UTILISATEUR', 'UTILISATEUR', 'ID_UTILISATEUR');

$_s->DD_MODULE_GABARIT->ID_MODULE_GABARIT('int', 11, 'unsigned', false, false, 'auto_increment')
    ->MOD_CODE('varchar', 30, '', false)
    ->GAB_CODE('varchar', 30, '', false)
    ->primary('PRIMARY', 'ID_MODULE_GABARIT')
    ->index('MOD_CODE', 'btree', 'MOD_CODE')
    ->index('GAB_CODE', 'btree', 'GAB_CODE')
    ->reference('DD_MODULE_GABARIT_DD_MODULE_ibfk', 'MOD_CODE', 'DD_MODULE', 'MOD_CODE')
    ->reference('DD_MODULE_GABARIT_DD_GABARIT_ibfk', 'GAB_CODE', 'DD_GABARIT', 'GAB_CODE');

$_s->DD_TEMPLATE_GABARIT->ID_TEMPLATE_GABARIT('int', 11, 'unsigned', false, false, 'auto_increment')
    ->TPL_CODE('varchar', 30, '', false)
    ->GAB_CODE('varchar', 30, '', false)
    ->primary('PRIMARY', 'ID_TEMPLATE_GABARIT')
    ->index('TPL_CODE', 'btree', 'TPL_CODE')
    ->index('GAB_CODE', 'btree', 'GAB_CODE')
    ->reference('DD_TEMPLATE_GABARIT_DD_TEMPLATE_ibfk', 'TPL_CODE', 'DD_TEMPLATE', 'TPL_CODE')
    ->reference('DD_TEMPLATE_GABARIT_DD_GABARIT_ibfk', 'GAB_CODE', 'DD_GABARIT', 'GAB_CODE');

$_s->STAT_GA_MEDIUM->GAM_CODE('varchar', 30, '', false)
    ->GAM_LIBELLE('varchar', 255, '', false)
    ->GAM_ORDRE('int', 11, 'unsigned', false)
    ->primary('PRIMARY', 'GAM_CODE');

$_s->STAT_GA_DETAIL->GAM_CODE('varchar', 30, '', false)
    ->SIT_CODE('varchar', 30, '', false)
    ->GAD_DATE('int', 11, 'unsigned', false)
    ->GAD_VISITS('varchar', 255, '', false)
    ->GAD_PAGEVIEWS('varchar', 255, '', false)
    ->GAD_TIMEONSITE('varchar', 255, '', false)
    ->GAD_NEWVISITS('varchar', 255, '', false)
    ->GAD_BOUNCES('varchar', 255, '', false)
    ->GAD_ENTRANCES('varchar', 255, '', false)
    ->primary('PRIMARY', 'GAM_CODE', 'GAD_DATE', 'SIT_CODE')
    ->index('GAM_CODE', 'btree', 'GAM_CODE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->index('GAD_DATE', 'btree', 'GAD_DATE')
    ->reference('STAT_GA_DETAIL_GAM_CODE_ibfk', 'GAM_CODE', 'STAT_GA_MEDIUM', 'GAM_CODE')
    ->reference('STAT_GA_DETAIL_SITE_CODE_ibfk', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');

$_s->ONLINEUSER->OLU_IP('varchar', 15, '', false)
    ->SIT_CODE('varchar', 30, '', false)
    ->OLU_DATELASTCONNEXION('int', 11, '', false)
    ->primary('PRIMARY', 'OLU_IP', 'SIT_CODE')
    ->index('SIT_CODE', 'btree', 'SIT_CODE')
    ->reference('ONLINEUSER_SIT_CODE', 'SIT_CODE', 'DD_SITE', 'SIT_CODE');
